databases:
  mongodb:
    address: 192.168.251.133:27017
    username: teddy
    password: teddy
    auth_db: teddy

mail:
  host: smtp.163.com
  port: 465
  username: zhsyourai@163.com
  password: 8228zhs..