apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "teddy.services.captcha.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "teddy.services.captcha.name" . }}
    helm.sh/chart: {{ include "teddy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "teddy.services.captcha.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "teddy.services.captcha.name" . }}
    helm.sh/chart: {{ include "teddy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ default "ClusterIP" .Values.services.captcha.type }}
    ports:
      - port: {{ default 8080 .Values.services.captcha.port }}
        targetPort: http
        protocol: TCP
        name: http
    selector:
      app.kubernetes.io/name: {{ include "teddy.services.captcha.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}

{{- $root := . -}}
{{- range .Values.services.captcha.deploys -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "teddy.services.captcha.name" $root }}
  labels:
    app.kubernetes.io/name: {{ include "teddy.services.captcha.name" $root }}
    app.kubernetes.io/version: {{ .image.tag }}
    helm.sh/chart: {{ include "teddy.chart" $root }}
    app.kubernetes.io/instance: {{ $root.Release.Name }}
    app.kubernetes.io/managed-by: {{ $root.Release.Service }}
spec:
  replicas: {{ default 1 $root.Values.services.captcha.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "teddy.services.captcha.name" $root }}
      app.kubernetes.io/instance: {{ $root.Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "teddy.services.captcha.name" $root }}
        app.kubernetes.io/instance: {{ $root.Release.Name }}
    spec:
      serviceAccountName: {{ include "teddy.services.captcha.name" $root }}
      containers:
        - name: {{ include "teddy.services.captcha.name" $root }}
          image: "{{ .image.repository }}:{{ .image.tag }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .resources | indent 12 }}
{{- with .nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
{{- end }}
