apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: default-http-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "todo.todo"
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: istio-system
spec:
  acme:
    # The ACME server URL
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: stage@istio.io
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging
    # Enable the HTTP-01 challenge provider
    http01: {}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: istio-ingressgateway-certs
  namespace: istio-system
spec:
  secretName: istio-ingressgateway-certs
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: bookinfo.example.com
  dnsNames:
  - bookinfo.example.com
  acme:
    config:
    - http01:
        ingressClass: none
      domains:
      - bookinfo.example.com
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: default-https-gateway
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
    hosts:
    - "todo.todo"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: default
spec:
  hosts:
  - "todo.todo"
  gateways:
  - default-https-gateway
  http:
  - match:
    - uri:
        prefix: /uaa
    route:
    - destination:
        port:
          number: 8080
        host: api-uaa
  - match:
    - uri:
        prefix: /base
    route:
    - destination:
        port:
          number: 8080
        host: api-base
  - match:
    - uri:
        prefix: /content
    route:
    - destination:
        port:
          number: 8080
        host: api-content
  - match:
    - uri:
        prefix: /message
    route:
    - destination:
        port:
          number: 8080
        host: api-message