{{- define "router" -}}
- match:
    - uri:
        prefix: /v1/auth/uaa
    - uri:
        prefix: /v1/uaa
  route:
    - destination:
        port:
          number: 8083
        host: {{ include "teddy.apis.uaa.name" .}}
- match:
    - uri:
        prefix: /v1/auth/base
    - uri:
        prefix: /v1/base
  route:
    - destination:
        port:
          number: 8080
        host: {{ include "teddy.apis.base.name" .}}
- match:
    - uri:
        prefix: /v1/auth/content
    - uri:
        prefix: /v1/content
  route:
    - destination:
        port:
          number: 8081
        host: {{ include "teddy.apis.content.name" .}}
- match:
    - uri:
        prefix: /v1/auth/message
    - uri:
        prefix: /v1/message
  route:
    - destination:
        port:
          number: 8082
        host: {{ include "teddy.apis.message.name" .}}
{{- end -}}

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: default-http-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - {{ .Values.gateway.host | quote }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: default
spec:
  hosts:
    - {{ .Values.gateway.host | quote }}
  gateways:
    - default-http-gateway
  http:
{{ include "router" . | indent 4 }}

{{- if .Values.gateway.tls }}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: istio-system
spec:
  acme:
    # The ACME server URL
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: stage@istio.io
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging
    # Enable the HTTP-01 challenge provider
    http01: {}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: istio-ingressgateway-certs
  namespace: istio-system
spec:
  secretName: istio-ingressgateway-certs
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: bookinfo.example.com
  dnsNames:
    - bookinfo.example.com
  acme:
    config:
      - http01:
          ingressClass: none
        domains:
          - bookinfo.example.com
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: default-https-gateway
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
        privateKey: /etc/istio/ingressgateway-certs/tls.key
      hosts:
        - {{ .Values.gateway.host }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: default
spec:
  hosts:
    - {{ .Values.gateway.host }}
  gateways:
    - default-https-gateway
  http:
{{ include "router" . | indent 4 }}
{{- end }}