apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "teddy.apis.message.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "teddy.apis.message.name" . }}
    helm.sh/chart: {{ include "teddy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "teddy.apis.message.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "teddy.apis.message.name" . }}
    helm.sh/chart: {{ include "teddy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ default "ClusterIP" .Values.apis.message.type }}
  ports:
    - port: {{ default 8080 .Values.apis.message.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "teddy.apis.message.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

{{- $root := . -}}
{{- range .Values.apis.message.deploys }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "teddy.apis.message.name" $root }}
  labels:
    app.kubernetes.io/name: {{ include "teddy.apis.message.name" $root }}
{{- if .image.tag }}
    app.kubernetes.io/version: {{ .image.tag }}
{{- end }}
    helm.sh/chart: {{ include "teddy.chart" $root }}
    app.kubernetes.io/instance: {{ $root.Release.Name }}
    app.kubernetes.io/managed-by: {{ $root.Release.Service }}
spec:
  replicas: {{ default 1 $root.Values.apis.message.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "teddy.apis.message.name" $root }}
      app.kubernetes.io/instance: {{ $root.Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "teddy.apis.message.name" $root }}
        app.kubernetes.io/instance: {{ $root.Release.Name }}
    spec:
      serviceAccountName: {{ include "teddy.apis.message.name" $root }}
      containers:
        - name: {{ include "teddy.apis.message.name" $root }}
{{- if .image.tag }}
          image: "{{ .image.repository }}:{{ .image.tag }}"
{{- else }}
          image: "{{ .image.repository }}"
{{- end }}
          imagePullPolicy: {{ .image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .resources | indent 12 }}
{{- with .nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
{{- end }}
