##################################################################################################
# mongodb Service entry
##################################################################################################
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-mongodb
spec:
  hosts:
    - external-mongodb.dummy
  addresses:
    - 10.107.206.141
  ports:
    - number: 27017
      name: mongodb
      protocol: MONGO
  location: MESH_INTERNAL
  resolution: STATIC
  endpoints:
    - address: 10.107.206.141