##################################################################################################
# mongodb Service entry
##################################################################################################
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-mongodb
spec:
  hosts:
    - external-mongodb.dummy
  addresses:
    - {{ .Values.mongodb.mongodbAddress -}}/32
  ports:
    - number: 27017
      name: tcp-1
      protocol: TCP
    - number: 27018
      name: tcp-2
      protocol: TCP
    - number: 27019
      name: tcp-3
      protocol: TCP
  location: MESH_EXTERNAL