apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: default
---
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: services-policy
spec:
  peers:
    - mtls: {}
  targets:
    - name: {{ include "teddy.services.captcha.name" . }}
    - name: {{ include "teddy.services.content.name" . }}
    - name: {{ include "teddy.services.message.name" . }}
    - name: {{ include "teddy.services.uaa.name" . }}
---
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: apis-policy
spec:
  peers:
    - mtls: {}
  targets:
    - name: {{ include "teddy.apis.base.name" . }}
      ports:
        - number: 8080
    - name: {{ include "teddy.apis.content.name" . }}
      ports:
        - number: 8081
    - name: {{ include "teddy.apis.message.name" . }}
      ports:
        - number: 8082
    - name: {{ include "teddy.apis.uaa.name" . }}
      ports:
        - number: 8083
  originIsOptional: true
  origins:
    - jwt:
        issuer: {{ .Values.apis.uaa.issuer }}
        jwksUri: {{ printf "http://%s%s" (include "teddy.apis.uaa.name" .) .Values.apis.uaa.jwksUriEndpoint }}
  principalBinding: USE_ORIGIN
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: RbacConfig
metadata:
  name: default
spec:
  mode: 'ON_WITH_INCLUSION'
  inclusion:
    namespaces: [{{ .Release.Namespace | quote }}]
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: admin
spec:
  rules:
    - services: ["*"]
      methods: ["*"]
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: binding-all-authenticated-admins
spec:
  subjects:
    - properties:
        source.principal: "*"
        request.auth.claims[roles]: "ADMIN"
  roleRef:
    kind: ServiceRole
    name: "admin"
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: user
spec:
  rules:
    - services: ["api-*"]
      methods: ["*"]
      paths:
        - "/v1/auth/*"
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: binding-all-teddy-api-authenticated-users
spec:
  subjects:
    - properties:
        source.principal: "*"
        request.auth.claims[roles]: "USER"
  roleRef:
    kind: ServiceRole
    name: "user"
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: anonymous-user
spec:
  rules:
    - services: ["api-*"]
      methods: ["*"]
      paths:
        - "/v1/anon/*"
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: binding-all-teddy-api-anonymous-users
spec:
  subjects:
    - user: "*"
  roleRef:
    kind: ServiceRole
    name: "anonymous-user"
---
##################################################################################################
# Uaa service role
##################################################################################################
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: {{ include "teddy.services.uaa.name" . }}-viewer
spec:
  rules:
    - services: [{{- printf "%s.%s.svc.cluster.local" (include "teddy.services.uaa.name" .) .Release.Namespace -}}]
      methods: ["POST"]
      paths:
        - "/com.teddy.srv.uaa.UAA/Get*"
        - "/com.teddy.srv.uaa.UAA/VerifyPassword"
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: {{ include "teddy.services.uaa.name" . }}-modifier
spec:
  rules:
    - services: [{{- printf "%s.%s.svc.cluster.local" (include "teddy.services.uaa.name" .) .Release.Namespace -}}]
      methods: ["POST"]
      paths:
        - "/com.teddy.srv.uaa.UAA/DeleteByUsername"
        - "/com.teddy.srv.uaa.UAA/ChangePassword"
        - "/com.teddy.srv.uaa.UAA/Register"
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: binding-{{ include "teddy.services.uaa.name" . }}-viewer
spec:
  subjects:
    - user: {{ printf "cluster.local/ns/%s/sa/%s" .Release.Namespace (include "teddy.apis.uaa.name" .) | quote }}
  roleRef:
    kind: ServiceRole
    name: {{ printf "%s-viewer" (include "teddy.services.uaa.name" .) | quote }}
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: binding-{{ include "teddy.services.uaa.name" . }}-modifier
spec:
  subjects:
    - user: {{ printf "cluster.local/ns/%s/sa/%s" .Release.Namespace (include "teddy.apis.uaa.name" .) | quote }}
  roleRef:
    kind: ServiceRole
    name: {{ printf "%s-modifier" (include "teddy.services.uaa.name" .) | quote }}
---
##################################################################################################
# content service role
##################################################################################################
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: {{ include "teddy.services.content.name" . }}-viewer
spec:
  rules:
    - services: [{{- printf "%s.%s.svc.cluster.local" (include "teddy.services.content.name" .) .Release.Namespace -}}]
      methods: ["POST"]
      paths:
        - "/com.teddy.srv.content.Content/Get*"
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: {{ include "teddy.services.content.name" . }}-modifier
spec:
  rules:
    - services: [{{- printf "%s.%s.svc.cluster.local" (include "teddy.services.content.name" .) .Release.Namespace -}}]
      methods: ["POST"]
      paths:
        - "/com.teddy.srv.content.Content/PublishInfo"
        - "/com.teddy.srv.content.Content/EditInfo"
        - "/com.teddy.srv.content.Content/DeleteInfo"
        - "/com.teddy.srv.content.Content/WatchInfo"
        - "/com.teddy.srv.content.Content/LikeInfo"
        - "/com.teddy.srv.content.Content/UnLikeInfo"
        - "/com.teddy.srv.content.Content/FavoriteInfo"
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: binding-{{ include "teddy.services.content.name" . }}-viewer
spec:
  subjects:
    - user: {{ printf "cluster.local/ns/%s/sa/%s" .Release.Namespace (include "teddy.apis.content.name" .) | quote }}
  roleRef:
    kind: ServiceRole
    name: {{ printf "%s-modifier" (include "teddy.services.content.name" .) | quote }}
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: binding-{{ include "teddy.services.content.name" . }}-modifier
spec:
  subjects:
    - user: {{ printf "cluster.local/ns/%s/sa/%s" .Release.Namespace (include "teddy.apis.content.name" .) | quote }}
  roleRef:
    kind: ServiceRole
    name: {{ printf "%s-modifier" (include "teddy.services.content.name" .) | quote }}
---
##################################################################################################
# message service role
##################################################################################################
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: {{ include "teddy.services.message.name" . }}-viewer
spec:
  rules:
    - services: [{{- printf "%s.%s.svc.cluster.local" (include "teddy.services.message.name" .) .Release.Namespace -}}]
      methods: ["POST"]
      paths:
        - "/com.teddy.srv.message.Message/Get*"
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: {{ include "teddy.services.message.name" . }}-sender
spec:
  rules:
    - services: [{{- printf "%s.%s.svc.cluster.local" (include "teddy.services.message.name" .) .Release.Namespace -}}]
      methods: ["POST"]
      paths:
        - "/com.teddy.srv.message.Message/Send*"
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: binding-{{ include "teddy.services.message.name" . }}-viewer
spec:
  subjects:
    - user: {{ printf "cluster.local/ns/%s/sa/%s" .Release.Namespace (include "teddy.apis.message.name" .) | quote }}
  roleRef:
    kind: ServiceRole
    name: {{ printf "%s-viewer" (include "teddy.services.content.name" .) | quote }}
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: binding-{{ include "teddy.services.message.name" . }}-modifier
spec:
  subjects:
    - user: {{ printf "cluster.local/ns/%s/sa/%s" .Release.Namespace (include "teddy.apis.message.name" .) | quote }}
    - user: {{ printf "cluster.local/ns/%s/sa/%s" .Release.Namespace (include "teddy.apis.uaa.name" .) | quote }}
  roleRef:
    kind: ServiceRole
    name: {{ printf "%s-sender" (include "teddy.services.content.name" .) | quote }}
---
##################################################################################################
# captcha service role
##################################################################################################
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: {{ include "teddy.services.captcha.name" . }}-viewer
spec:
  rules:
    - services: [{{- printf "%s.%s.svc.cluster.local" (include "teddy.services.captcha.name" .) .Release.Namespace -}}]
      methods: ["POST"]
      paths:
        - "/com.teddy.srv.captcha.Captcha/Get*"
        - "/com.teddy.srv.captcha.Captcha/Verify"
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: binding-{{ include "teddy.services.captcha.name" . }}-viewer
spec:
  subjects:
    - user: {{ printf "cluster.local/ns/%s/sa/%s" .Release.Namespace (include "teddy.apis.uaa.name" .) | quote }}
    - user: {{ printf "cluster.local/ns/%s/sa/%s" .Release.Namespace (include "teddy.apis.base.name" .) | quote }}
  roleRef:
    kind: ServiceRole
    name: {{ include "teddy.services.captcha.name" . }}-viewer

