{{- $root := . -}}
{{- $use_subsets := 0 -}}
##################################################################################################
# base api traffic
##################################################################################################
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "teddy.apis.base.name" . }}
spec:
  host: {{ include "teddy.apis.base.name" . }}
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
{{- $use_subsets := 0 -}}
{{- range .Values.apis.base.deploys -}}
  {{- if .image.tag -}}
    {{- $use_subsets := 1 -}}
  {{- else -}}
    {{- $use_subsets := 0 -}}
  {{- end -}}
{{- end -}}
{{- if eq $use_subsets 1 }}
  subsets:
{{- range .Values.apis.base.deploys -}}
  {{- if .image.tag }}
    - name: {{ .image.tag }}
      labels:
        app.kubernetes.io/version: {{ .image.tag }}
  {{- end -}}
{{- end -}}
{{- end }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "teddy.apis.base.name" . }}
spec:
  hosts:
    - {{ include "teddy.apis.base.name" . }}
  http:
{{- range .Values.apis.base.deploys }}
    {{- if and .traffic.headers (not .traffic.weight) }}
    - timeout: {{ .traffic.timeout }}
      match:
        - headers:
          {{ toYaml .traffic.headers | indent 5 -}}
      route:
        - destination:
            host: {{ include "teddy.apis.base.name" $root }}
            {{- if .image.tag }}
            subset: {{ .image.tag }}
            {{- end }}
    {{- else if and (not .traffic.headers) .traffic.weight }}
    - timeout: {{ .traffic.timeout }}
      route:
        - destination:
            host: {{ include "teddy.apis.base.name" $root }}
            {{- if .image.tag }}
            subset: {{ .image.tag }}
            {{- end }}
          weight: {{ .traffic.weight }}
    {{- else if and (not .traffic.headers) (not .traffic.weight) }}
    - timeout: {{ .traffic.timeout }}
      route:
        - destination:
            host: {{ include "teddy.apis.base.name" $root }}
            {{- if .image.tag }}
            subset: {{ .image.tag }}
            {{- end }}
    {{- end }}
{{- end }}
---
##################################################################################################
# uaa api traffic
##################################################################################################
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "teddy.apis.uaa.name" . }}
spec:
  host: {{ include "teddy.apis.uaa.name" . }}
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
{{- $use_subsets := 0 -}}
{{- range .Values.apis.uaa.deploys -}}
  {{- if .image.tag -}}
    {{- $use_subsets := 1 -}}
  {{- else -}}
    {{- $use_subsets := 0 -}}
  {{- end -}}
{{- end -}}
{{- if eq $use_subsets 1 }}
  subsets:
{{- range .Values.apis.uaa.deploys -}}
  {{- if .image.tag }}
    - name: {{ .image.tag }}
      labels:
        app.kubernetes.io/version: {{ .image.tag }}
  {{- end -}}
{{- end -}}
{{- end }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "teddy.apis.uaa.name" . }}
spec:
  hosts:
    - {{ include "teddy.apis.uaa.name" . }}
  http:
{{- range .Values.apis.uaa.deploys }}
    {{- if and .traffic.headers (not .traffic.weight) }}
    - timeout: {{ .traffic.timeout }}
      match:
        - headers:
          {{ toYaml .traffic.headers | indent 5 -}}
      route:
        - destination:
            host: {{ include "teddy.apis.uaa.name" $root }}
            {{- if .image.tag }}
            subset: {{ .image.tag }}
            {{- end }}
    {{- else if and (not .traffic.headers) .traffic.weight }}
    - timeout: {{ .traffic.timeout }}
      route:
        - destination:
            host: {{ include "teddy.apis.uaa.name" $root }}
            {{- if .image.tag }}
            subset: {{ .image.tag }}
            {{- end }}
          weight: {{ .traffic.weight }}
    {{- else if and (not .traffic.headers) (not .traffic.weight) }}
    - timeout: {{ .traffic.timeout }}
      route:
        - destination:
            host: {{ include "teddy.apis.uaa.name" $root }}
            {{- if .image.tag }}
            subset: {{ .image.tag }}
            {{- end }}
    {{- end }}
{{- end }}
---
##################################################################################################
# content api traffic
##################################################################################################
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "teddy.apis.content.name" . }}
spec:
  host: {{ include "teddy.apis.content.name" . }}
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
{{- $use_subsets := 0 -}}
{{- range .Values.apis.content.deploys -}}
  {{- if .image.tag -}}
    {{- $use_subsets := 1 -}}
  {{- else -}}
    {{- $use_subsets := 0 -}}
  {{- end -}}
{{- end -}}
{{- if eq $use_subsets 1 }}
  subsets:
{{- range .Values.apis.content.deploys -}}
  {{- if .image.tag }}
    - name: {{ .image.tag }}
      labels:
        app.kubernetes.io/version: {{ .image.tag }}
  {{- end -}}
{{- end -}}
{{- end }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "teddy.apis.content.name" . }}
spec:
  hosts:
    - {{ include "teddy.apis.content.name" . }}
  http:
{{- range .Values.apis.content.deploys }}
    {{- if and .traffic.headers (not .traffic.weight) }}
    - timeout: {{ .traffic.timeout }}
      match:
        - headers:
          {{ toYaml .traffic.headers | indent 5 -}}
      route:
        - destination:
            host: {{ include "teddy.apis.content.name" $root }}
            {{- if .image.tag }}
            subset: {{ .image.tag }}
            {{- end }}
    {{- else if and (not .traffic.headers) .traffic.weight }}
    - timeout: {{ .traffic.timeout }}
      route:
        - destination:
            host: {{ include "teddy.apis.content.name" $root }}
            {{- if .image.tag }}
            subset: {{ .image.tag }}
            {{- end }}
          weight: {{ .traffic.weight }}
    {{- else if and (not .traffic.headers) (not .traffic.weight) }}
    - timeout: {{ .traffic.timeout }}
      route:
        - destination:
            host: {{ include "teddy.apis.content.name" $root }}
            {{- if .image.tag }}
            subset: {{ .image.tag }}
            {{- end }}
    {{- end }}
{{- end }}
---
##################################################################################################
# message api traffic
##################################################################################################
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "teddy.apis.message.name" . }}
spec:
  host: {{ include "teddy.apis.message.name" . }}
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
{{- $use_subsets := 0 -}}
{{- range .Values.apis.message.deploys -}}
  {{- if .image.tag -}}
    {{- $use_subsets := 1 -}}
  {{- else -}}
    {{- $use_subsets := 0 -}}
  {{- end -}}
{{- end -}}
{{- if eq $use_subsets 1 }}
  subsets:
{{- range .Values.apis.message.deploys -}}
  {{- if .image.tag }}
    - name: {{ .image.tag }}
      labels:
        app.kubernetes.io/version: {{ .image.tag }}
  {{- end -}}
{{- end -}}
{{- end }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "teddy.apis.message.name" . }}
spec:
  hosts:
    - {{ include "teddy.apis.message.name" . }}
  http:
{{- range .Values.apis.message.deploys }}
    {{- if and .traffic.headers (not .traffic.weight) }}
    - timeout: {{ .traffic.timeout }}
      match:
        - headers:
          {{ toYaml .traffic.headers | indent 5 -}}
      route:
        - destination:
            host: {{ include "teddy.apis.message.name" $root }}
            {{- if .image.tag }}
            subset: {{ .image.tag }}
            {{- end }}
    {{- else if and (not .traffic.headers) .traffic.weight }}
    - timeout: {{ .traffic.timeout }}
      route:
        - destination:
            host: {{ include "teddy.apis.message.name" $root }}
            {{- if .image.tag }}
            subset: {{ .image.tag }}
            {{- end }}
          weight: {{ .traffic.weight }}
    {{- else if and (not .traffic.headers) (not .traffic.weight) }}
    - timeout: {{ .traffic.timeout }}
      route:
        - destination:
            host: {{ include "teddy.apis.message.name" $root }}
            {{- if .image.tag }}
            subset: {{ .image.tag }}
            {{- end }}
    {{- end }}
{{- end }}
---
##################################################################################################
# uaa service traffic
##################################################################################################
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "teddy.services.uaa.name" . }}
spec:
  host: {{ include "teddy.services.uaa.name" . }}
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
  subsets:
{{- $use_subsets := 0 -}}
{{- range .Values.services.uaa.deploys -}}
  {{- if .image.tag -}}
    {{- $use_subsets := 1 -}}
  {{- else -}}
    {{- $use_subsets := 0 -}}
  {{- end -}}
{{- end -}}
{{- if eq $use_subsets 1 }}
  subsets:
{{- range .Values.services.uaa.deploys -}}
  {{- if .image.tag }}
    - name: {{ .image.tag }}
      labels:
        app.kubernetes.io/version: {{ .image.tag }}
  {{- end -}}
{{- end -}}
{{- end }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "teddy.services.uaa.name" . }}
spec:
  hosts:
    - {{ include "teddy.services.uaa.name" . }}
  http:
{{- range .Values.services.uaa.deploys }}
    {{- if .traffic.weight }}
    - timeout: {{ .traffic.timeout }}
      route:
        - destination:
            host: {{ include "teddy.services.uaa.name" $root }}
            {{- if .image.tag }}
            subset: {{ .image.tag }}
            {{- end }}
          weight: {{ .traffic.weight }}
    {{- else }}
    - timeout: {{ .traffic.timeout }}
      route:
        - destination:
            host: {{ include "teddy.services.uaa.name" $root }}
            {{- if .image.tag }}
            subset: {{ .image.tag }}
            {{- end }}
    {{- end }}
{{- end }}
---
##################################################################################################
# message service traffic
##################################################################################################
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "teddy.services.message.name" . }}
spec:
  host: {{ include "teddy.services.message.name" . }}
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
{{- $use_subsets := 0 -}}
{{- range .Values.services.message.deploys -}}
  {{- if .image.tag -}}
    {{- $use_subsets := 1 -}}
  {{- else -}}
    {{- $use_subsets := 0 -}}
  {{- end -}}
{{- end -}}
{{- if eq $use_subsets 1 }}
  subsets:
{{- range .Values.services.message.deploys -}}
  {{- if .image.tag }}
    - name: {{ .image.tag }}
      labels:
        app.kubernetes.io/version: {{ .image.tag }}
  {{- end -}}
{{- end -}}
{{- end }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "teddy.services.message.name" . }}
spec:
  hosts:
    - {{ include "teddy.services.message.name" . }}
  http:
{{- range .Values.services.message.deploys }}
    {{- if .traffic.weight }}
    - timeout: {{ .traffic.timeout }}
      route:
        - destination:
            host: {{ include "teddy.services.message.name" $root }}
            {{- if .image.tag }}
            subset: {{ .image.tag }}
            {{- end }}
          weight: {{ .traffic.weight }}
    {{- else }}
    - timeout: {{ .traffic.timeout }}
      route:
        - destination:
            host: {{ include "teddy.services.message.name" $root }}
            {{- if .image.tag }}
            subset: {{ .image.tag }}
            {{- end }}
    {{- end }}
{{- end }}
---
##################################################################################################
# content service traffic
##################################################################################################
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "teddy.services.content.name" . }}
spec:
  host: {{ include "teddy.services.content.name" . }}
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
{{- $use_subsets := 0 -}}
{{- range .Values.services.content.deploys -}}
  {{- if .image.tag -}}
    {{- $use_subsets := 1 -}}
  {{- else -}}
    {{- $use_subsets := 0 -}}
  {{- end -}}
{{- end -}}
{{- if eq $use_subsets 1 }}
  subsets:
{{- range .Values.services.content.deploys -}}
  {{- if .image.tag }}
    - name: {{ .image.tag }}
      labels:
        app.kubernetes.io/version: {{ .image.tag }}
  {{- end -}}
{{- end -}}
{{- end }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "teddy.services.content.name" . }}
spec:
  hosts:
    - {{ include "teddy.services.content.name" . }}
  http:
{{- range .Values.services.content.deploys }}
    {{- if .traffic.weight }}
    - timeout: {{ .traffic.timeout }}
      route:
        - destination:
            host: {{ include "teddy.services.content.name" $root }}
            {{- if .image.tag }}
            subset: {{ .image.tag }}
            {{- end }}
          weight: {{ .traffic.weight }}
    {{- else }}
    - timeout: {{ .traffic.timeout }}
      route:
        - destination:
            host: {{ include "teddy.services.content.name" $root }}
            {{- if .image.tag }}
            subset: {{ .image.tag }}
            {{- end }}
    {{- end }}
{{- end }}
---
##################################################################################################
# captcha service traffic
##################################################################################################
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "teddy.services.captcha.name" . }}
spec:
  host: {{ include "teddy.services.captcha.name" . }}
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
  subsets:
{{- $use_subsets := 0 -}}
{{- range .Values.services.captcha.deploys -}}
  {{- if .image.tag -}}
    {{- $use_subsets := 1 -}}
  {{- else -}}
    {{- $use_subsets := 0 -}}
  {{- end -}}
{{- end -}}
{{- if eq $use_subsets 1 }}
  subsets:
{{- range .Values.services.captcha.deploys -}}
  {{- if .image.tag }}
    - name: {{ .image.tag }}
      labels:
        app.kubernetes.io/version: {{ .image.tag }}
  {{- end -}}
{{- end -}}
{{- end }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "teddy.services.captcha.name" . }}
spec:
  hosts:
    - {{ include "teddy.services.captcha.name" . }}
  http:
{{- range .Values.services.captcha.deploys }}
    {{- if .traffic.weight }}
    - timeout: {{ .traffic.timeout }}
      route:
        - destination:
            host: {{ include "teddy.services.captcha.name" $root }}
            {{- if .image.tag }}
            subset: {{ .image.tag }}
            {{- end }}
          weight: {{ .traffic.weight }}
    {{- else }}
    - timeout: {{ .traffic.timeout }}
      route:
        - destination:
            host: {{ include "teddy.services.captcha.name" $root }}
            {{- if .image.tag }}
            subset: {{ .image.tag }}
            {{- end }}
    {{- end }}
{{- end }}