{{- $root := . -}}
##################################################################################################
# base api traffic
##################################################################################################
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "teddy.apis.base.name" . }}
spec:
  host: {{ include "teddy.apis.base.name" . }}
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
  subsets:
{{- range .Values.apis.base.deploys }}
    - name: {{ .image.tag }}
      labels:
        app.kubernetes.io/version: {{ .image.tag }}
{{- end }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "teddy.apis.base.name" . }}
spec:
  hosts:
    - {{ include "teddy.apis.base.name" . }}
  http:
{{- range .Values.apis.base.deploys }}
    {{- if and .traffic.headers (not .traffic.weight) }}
    - timeout: {{ .traffic.timeout }}
      match:
        - headers:
          {{ toYaml .traffic.headers | indent 5 -}}
      route:
        - destination:
            host: {{ include "teddy.apis.base.name" $root }}
    {{- end }}
{{- end }}
{{- range .Values.apis.base.deploys }}
    {{- if and (not .traffic.headers) .traffic.weight }}
    - timeout: {{ .traffic.timeout }}
      route:
        - destination:
            host: {{ include "teddy.apis.base.name" $root }}
            subset: {{ .image.tag }}
          weight: {{ .traffic.weight }}
    {{- end }}
{{- end }}
{{- range .Values.apis.base.deploys }}
    {{- if and (not .traffic.headers) (not .traffic.weight) }}
    - timeout: {{ .traffic.timeout }}
      route:
        - destination:
            host: {{ include "teddy.apis.base.name" $root }}
            subset: {{ .image.tag }}
    {{- end }}
{{- end }}
---
##################################################################################################
# uaa api traffic
##################################################################################################
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "teddy.apis.uaa.name" . }}
spec:
  host: {{ include "teddy.apis.uaa.name" . }}
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
  subsets:
{{- range .Values.apis.uaa.deploys }}
    - name: {{ .image.tag }}
      labels:
        app.kubernetes.io/version: {{ .image.tag }}
{{- end }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "teddy.apis.uaa.name" . }}
spec:
  hosts:
    - {{ include "teddy.apis.uaa.name" . }}
  http:
{{- range .Values.apis.uaa.deploys }}
    {{- if and .traffic.headers (not .traffic.weight) }}
    - timeout: {{ .traffic.timeout }}
      match:
        - headers:
          {{ toYaml .traffic.headers | indent 5 -}}
      route:
        - destination:
            host: {{ include "teddy.apis.uaa.name" $root }}
    {{- end }}
{{- end }}
{{- range .Values.apis.uaa.deploys }}
    {{- if and (not .traffic.headers) .traffic.weight }}
    - timeout: {{ .traffic.timeout }}
      route:
        - destination:
            host: {{ include "teddy.apis.uaa.name" $root }}
            subset: {{ .image.tag }}
          weight: {{ .traffic.weight }}
    {{- end }}
{{- end }}
{{- range .Values.apis.uaa.deploys }}
    {{- if and (not .traffic.headers) (not .traffic.weight) }}
    - timeout: {{ .traffic.timeout }}
      route:
        - destination:
            host: {{ include "teddy.apis.uaa.name" $root }}
            subset: {{ .image.tag }}
    {{- end }}
{{- end }}
---
##################################################################################################
# content api traffic
##################################################################################################
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "teddy.apis.content.name" . }}
spec:
  host: {{ include "teddy.apis.content.name" . }}
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
  subsets:
{{- range .Values.apis.content.deploys }}
    - name: {{ .image.tag }}
      labels:
        app.kubernetes.io/version: {{ .image.tag }}
{{- end }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "teddy.apis.content.name" . }}
spec:
  hosts:
    - {{ include "teddy.apis.content.name" . }}
  http:
{{- range .Values.apis.content.deploys }}
    {{- if and .traffic.headers (not .traffic.weight) }}
    - timeout: {{ .traffic.timeout }}
      match:
        - headers:
          {{ toYaml .traffic.headers | indent 5 -}}
      route:
        - destination:
            host: {{ include "teddy.apis.content.name" $root }}
    {{- end }}
{{- end }}
{{- range .Values.apis.content.deploys }}
    {{- if and (not .traffic.headers) .traffic.weight }}
    - timeout: {{ .traffic.timeout }}
      route:
        - destination:
            host: {{ include "teddy.apis.content.name" $root }}
            subset: {{ .image.tag }}
          weight: {{ .traffic.weight }}
    {{- end }}
{{- end }}
{{- range .Values.apis.content.deploys }}
    {{- if and (not .traffic.headers) (not .traffic.weight) }}
    - timeout: {{ .traffic.timeout }}
      route:
        - destination:
            host: {{ include "teddy.apis.content.name" $root }}
            subset: {{ .image.tag }}
    {{- end }}
{{- end }}
---
##################################################################################################
# message api traffic
##################################################################################################
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "teddy.apis.message.name" . }}
spec:
  host: {{ include "teddy.apis.message.name" . }}
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
  subsets:
{{- range .Values.apis.message.deploys }}
    - name: {{ .image.tag }}
      labels:
        app.kubernetes.io/version: {{ .image.tag }}
{{- end }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "teddy.apis.message.name" . }}
spec:
  hosts:
    - {{ include "teddy.apis.message.name" . }}
  http:
{{- range .Values.apis.message.deploys }}
    {{- if and .traffic.headers (not .traffic.weight) }}
    - timeout: {{ .traffic.timeout }}
      match:
        - headers:
          {{ toYaml .traffic.headers | indent 5 -}}
      route:
        - destination:
            host: {{ include "teddy.apis.message.name" $root }}
    {{- end }}
{{- end }}
{{- range .Values.apis.message.deploys }}
    {{- if and (not .traffic.headers) .traffic.weight }}
    - timeout: {{ .traffic.timeout }}
      route:
        - destination:
            host: {{ include "teddy.apis.message.name" $root }}
            subset: {{ .image.tag }}
          weight: {{ .traffic.weight }}
    {{- end }}
{{- end }}
{{- range .Values.apis.message.deploys }}
    {{- if and (not .traffic.headers) (not .traffic.weight) }}
    - timeout: {{ .traffic.timeout }}
      route:
        - destination:
            host: {{ include "teddy.apis.message.name" $root }}
            subset: {{ .image.tag }}
    {{- end }}
{{- end }}
---
##################################################################################################
# uaa service traffic
##################################################################################################
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "teddy.services.uaa.name" . }}
spec:
  host: {{ include "teddy.services.uaa.name" . }}
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
  subsets:
{{- range .Values.services.uaa.deploys }}
    - name: {{ .image.tag }}
      labels:
        app.kubernetes.io/version: {{ .image.tag }}
{{- end }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "teddy.services.uaa.name" . }}
spec:
  hosts:
    - {{ include "teddy.services.uaa.name" . }}
  http:
{{- range .Values.services.uaa.deploys }}
    {{- if .traffic.weight }}
    - timeout: {{ .traffic.timeout }}
      route:
        - destination:
            host: {{ include "teddy.services.uaa.name" $root }}
            subset: {{ .image.tag }}
          weight: {{ .traffic.weight }}
    {{- end }}
{{- end }}
{{- range .Values.services.uaa.deploys }}
    {{- if not .traffic.weight }}
    - timeout: {{ .traffic.timeout }}
      route:
        - destination:
            host: {{ include "teddy.services.uaa.name" $root }}
            subset: {{ .image.tag }}
    {{- end }}
{{- end }}
---
##################################################################################################
# message service traffic
##################################################################################################
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "teddy.services.message.name" . }}
spec:
  host: {{ include "teddy.services.message.name" . }}
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
  subsets:
{{- range .Values.services.message.deploys }}
    - name: {{ .image.tag }}
      labels:
        app.kubernetes.io/version: {{ .image.tag }}
{{- end }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "teddy.services.message.name" . }}
spec:
  hosts:
    - {{ include "teddy.services.message.name" . }}
  http:
{{- range .Values.services.message.deploys }}
    {{- if .traffic.weight }}
    - timeout: {{ .traffic.timeout }}
      route:
        - destination:
            host: {{ include "teddy.services.message.name" $root }}
            subset: {{ .image.tag }}
          weight: {{ .traffic.weight }}
    {{- end }}
{{- end }}
{{- range .Values.services.message.deploys }}
    {{- if not .traffic.weight }}
    - timeout: {{ .traffic.timeout }}
      route:
        - destination:
            host: {{ include "teddy.services.message.name" $root }}
            subset: {{ .image.tag }}
    {{- end }}
{{- end }}
---
##################################################################################################
# content service traffic
##################################################################################################
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "teddy.services.content.name" . }}
spec:
  host: {{ include "teddy.services.content.name" . }}
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
  subsets:
{{- range .Values.services.content.deploys }}
    - name: {{ .image.tag }}
      labels:
        app.kubernetes.io/version: {{ .image.tag }}
{{- end }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "teddy.services.content.name" . }}
spec:
  hosts:
    - {{ include "teddy.services.content.name" . }}
  http:
{{- range .Values.services.content.deploys }}
    {{- if .traffic.weight }}
    - timeout: {{ .traffic.timeout }}
      route:
        - destination:
            host: {{ include "teddy.services.content.name" $root }}
            subset: {{ .image.tag }}
          weight: {{ .traffic.weight }}
    {{- end }}
{{- end }}
{{- range .Values.services.content.deploys }}
    {{- if not .traffic.weight }}
    - timeout: {{ .traffic.timeout }}
      route:
        - destination:
            host: {{ include "teddy.services.content.name" $root }}
            subset: {{ .image.tag }}
    {{- end }}
{{- end }}
---
##################################################################################################
# captcha service traffic
##################################################################################################
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "teddy.services.captcha.name" . }}
spec:
  host: {{ include "teddy.services.captcha.name" . }}
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
  subsets:
{{- range .Values.services.captcha.deploys }}
    - name: {{ .image.tag }}
      labels:
        app.kubernetes.io/version: {{ .image.tag }}
{{- end }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "teddy.services.captcha.name" . }}
spec:
  hosts:
    - {{ include "teddy.services.captcha.name" . }}
  http:
{{- range .Values.services.captcha.deploys }}
    {{- if .traffic.weight }}
    - timeout: {{ .traffic.timeout }}
      route:
        - destination:
            host: {{ include "teddy.services.captcha.name" $root }}
            subset: {{ .image.tag }}
          weight: {{ .traffic.weight }}
    {{- end }}
{{- end }}
{{- range .Values.services.captcha.deploys }}
    {{- if not .traffic.weight }}
    - timeout: {{ .traffic.timeout }}
      route:
        - destination:
            host: {{ include "teddy.services.captcha.name" $root }}
            subset: {{ .image.tag }}
    {{- end }}
{{- end }}