##################################################################################################
# base api traffic
##################################################################################################
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "teddy.apis.base.name" . }}
spec:
  host: {{ include "teddy.apis.base.name" . }}
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "teddy.apis.base.name" . }}
spec:
  hosts:
    - {{ include "teddy.apis.base.name" . }}
  http:
    - timeout: {{ .Values.apis.base.deploy.traffic.timeout }}
      route:
        - destination:
            host: {{ include "teddy.apis.base.name" . }}
---
##################################################################################################
# uaa api traffic
##################################################################################################
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "teddy.apis.uaa.name" . }}
spec:
  host: {{ include "teddy.apis.uaa.name" . }}
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "teddy.apis.uaa.name" . }}
spec:
  hosts:
    - {{ include "teddy.apis.uaa.name" . }}
  http:
    - timeout: {{ .Values.apis.uaa.deploy.traffic.timeout }}
      route:
        - destination:
            host: {{ include "teddy.apis.uaa.name" . }}
---
##################################################################################################
# content api traffic
##################################################################################################
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "teddy.apis.content.name" . }}
spec:
  host: {{ include "teddy.apis.content.name" . }}
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "teddy.apis.content.name" . }}
spec:
  hosts:
    - {{ include "teddy.apis.content.name" . }}
  http:
    - timeout: {{ .Values.apis.content.deploy.traffic.timeout }}
      route:
        - destination:
            host: {{ include "teddy.apis.content.name" . }}
---
##################################################################################################
# message api traffic
##################################################################################################
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "teddy.apis.message.name" . }}
spec:
  host: {{ include "teddy.apis.message.name" . }}
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "teddy.apis.message.name" . }}
spec:
  hosts:
    - {{ include "teddy.apis.message.name" . }}
  http:
    - timeout: {{ .Values.apis.message.deploy.traffic.timeout }}
      route:
        - destination:
            host: {{ include "teddy.apis.message.name" . }}
---
##################################################################################################
# uaa service traffic
##################################################################################################
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "teddy.services.uaa.name" . }}
spec:
  host: {{ include "teddy.services.uaa.name" . }}
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "teddy.services.uaa.name" . }}
spec:
  hosts:
    - {{ include "teddy.services.uaa.name" . }}
  http:
    - timeout: {{ .Values.services.uaa.deploy.traffic.timeout }}
      route:
        - destination:
            host: {{ include "teddy.services.uaa.name" . }}
---
##################################################################################################
# message service traffic
##################################################################################################
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "teddy.services.message.name" . }}
spec:
  host: {{ include "teddy.services.message.name" . }}
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "teddy.services.message.name" . }}
spec:
  hosts:
    - {{ include "teddy.services.message.name" . }}
  http:
    - timeout: {{ .Values.services.message.deploy.traffic.timeout }}
      route:
        - destination:
            host: {{ include "teddy.services.message.name" . }}
---
##################################################################################################
# content service traffic
##################################################################################################
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "teddy.services.content.name" . }}
spec:
  host: {{ include "teddy.services.content.name" . }}
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "teddy.services.content.name" . }}
spec:
  hosts:
    - {{ include "teddy.services.content.name" . }}
  http:
    - timeout: {{ .Values.services.content.deploy.traffic.timeout }}
      route:
        - destination:
            host: {{ include "teddy.services.content.name" . }}
---
##################################################################################################
# captcha service traffic
##################################################################################################
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "teddy.services.captcha.name" . }}
spec:
  host: {{ include "teddy.services.captcha.name" . }}
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "teddy.services.captcha.name" . }}
spec:
  hosts:
    - {{ include "teddy.services.captcha.name" . }}
  http:
    - timeout: {{ .Values.services.captcha.deploy.traffic.timeout }}
      route:
        - destination:
            host: {{ include "teddy.services.captcha.name" . }}
