consul:
  command: -server -bootstrap -rejoin
  image: progrium/consul:latest
  ports:
  - "8300:8300"
  - "8400:8400"
  - "8500:8500"
  - "8600:53/udp"

micro:
  command: --registry_address=consul:8500 api --handler=web
  image: microhq/micro:latest
  links:
  - consul
  - api
  ports:
  - "8080:8080"

api-base:
  build: ./api/base
  command: --registry_address=consul:8500
  links:
  - consul
  - captcha

api-content:
  build: ./api/content
  command: --registry_address=consul:8500
  links:
  - consul
  - message
  - captcha

api-message:
  build: ./api/message
  command: --registry_address=consul:8500
  links:
  - consul
  - message
  - captcha

api-uaa:
  build: ./api/uaa
    command: --registry_address=consul:8500
    links:
    - consul
    - uaa
    - message
    - captcha
message:
  build: ./message
  command: --registry_address=consul:8500
  links:
  - consul

uaa:
  build: ./uaa
  command: --registry_address=consul:8500
  links:
  - consul

content:
  build: ./content
  command: --registry_address=consul:8500
  links:
  - consul

captcha:
  build: ./captcha
  command: --registry_address=consul:8500
  links:
  - consul