apiVersion: skaffold/v1alpha5
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: zhsyourai/uaa-srv
      context: ./uaa/
    - image: zhsyourai/uaa-api
      context: ./api/uaa
    - image: zhsyourai/message-srv
      context: ./message
    - image: zhsyourai/message-api
      context: ./api/message
    - image: zhsyourai/content-srv
      context: ./content
    - image: zhsyourai/content-api
      context: ./api/content
    - image: zhsyourai/captcha-srv
      context: ./captcha
    - image: zhsyourai/base-api
      context: ./api/base
deploy:
  helm:
    releases:
      - name: teddy
        chartPath: install/teddy
        values:
          apis.base.deploy.image.repository: zhsyourai/base-api
          apis.content.deploy.image.repository: zhsyourai/content-api
          apis.message.deploy.image.repository: zhsyourai/message-api
          apis.uaa.deploy.image.repository: zhsyourai/uaa-api
          services.captcha.deploy.image.repository: zhsyourai/captcha-srv
          services.content.deploy.image.repository: zhsyourai/content-srv
          services.message.deploy.image.repository: zhsyourai/message-srv
          services.uaa.deploy.image.repository: zhsyourai/uaa-srv
        #wait: true
        #valuesFiles:
        #- helm-skaffold-values.yaml
        #values:
          #image: gcr.io/k8s-skaffold/skaffold-helm
          #recreatePods will pass --recreate-pods to helm upgrade
          #recreatePods: true
          #overrides builds an override values.yaml file to run with the helm deploy
          #overrides:
          # some:
          #   key: someValue
          #setValues get appended to the helm deploy with --set.
          #setValues:
          #some.key: someValue