apiVersion: skaffold/v1alpha5
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: zhsyourai/srv-uaa
      context: ./uaa/
    - image: zhsyourai/api-uaa
      context: ./api/uaa
    - image: zhsyourai/srv-message
      context: ./message
    - image: zhsyourai/api-message
      context: ./api/message
    - image: zhsyourai/srv-content
      context: ./content
    - image: zhsyourai/api-content
      context: ./api/content
    - image: zhsyourai/srv-captcha
      context: ./captcha
    - image: zhsyourai/api-base
      context: ./api/base
deploy:
  helm:
    releases:
      - name: teddy
        chartPath: install/teddy
        values:
          apis.base.deploy.image.repository: zhsyourai/api-base
          apis.content.deploy.image.repository: zhsyourai/api-content
          apis.message.deploy.image.repository: zhsyourai/api-message
          apis.uaa.deploy.image.repository: zhsyourai/api-uaa
          services.captcha.deploy.image.repository: zhsyourai/srv-captcha
          services.content.deploy.image.repository: zhsyourai/srv-content
          services.message.deploy.image.repository: zhsyourai/srv-message
          services.uaa.deploy.image.repository: zhsyourai/srv-uaa
        #wait: true
        #valuesFiles:
        #- helm-skaffold-values.yaml
        #values:
          #image: gcr.io/k8s-skaffold/skaffold-helm
          #recreatePods will pass --recreate-pods to helm upgrade
          #recreatePods: true
          #overrides builds an override values.yaml file to run with the helm deploy
          #overrides:
          # some:
          #   key: someValue
          #setValues get appended to the helm deploy with --set.
          #setValues:
          #some.key: someValue