[prune]
  go-tests = true

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.6"

[[constraint]]
  name = "github.com/mongodb/mongo-go-driver"
  version = "0.0.18"

[[constraint]]
  branch = "master"
  name = "github.com/dchest/captcha"
