// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/notify.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	proto/notify.proto

It has these top-level messages:
	SendEmailRequest
	SendInBoxRequest
	SendNotifyRequest
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"
import _ "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = google_protobuf.Empty{}

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Notify service

type NotifyService interface {
	SendEmail(ctx context.Context, in *SendEmailRequest, opts ...client.CallOption) (*google_protobuf.Empty, error)
	SendInBox(ctx context.Context, in *SendInBoxRequest, opts ...client.CallOption) (*google_protobuf.Empty, error)
	SendNotify(ctx context.Context, in *SendNotifyRequest, opts ...client.CallOption) (*google_protobuf.Empty, error)
}

type notifyService struct {
	c    client.Client
	name string
}

func NewNotifyService(name string, c client.Client) NotifyService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "com.teddy.srv.notify"
	}
	return &notifyService{
		c:    c,
		name: name,
	}
}

func (c *notifyService) SendEmail(ctx context.Context, in *SendEmailRequest, opts ...client.CallOption) (*google_protobuf.Empty, error) {
	req := c.c.NewRequest(c.name, "Notify.SendEmail", in)
	out := new(google_protobuf.Empty)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyService) SendInBox(ctx context.Context, in *SendInBoxRequest, opts ...client.CallOption) (*google_protobuf.Empty, error) {
	req := c.c.NewRequest(c.name, "Notify.SendInBox", in)
	out := new(google_protobuf.Empty)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyService) SendNotify(ctx context.Context, in *SendNotifyRequest, opts ...client.CallOption) (*google_protobuf.Empty, error) {
	req := c.c.NewRequest(c.name, "Notify.SendNotify", in)
	out := new(google_protobuf.Empty)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Notify service

type NotifyHandler interface {
	SendEmail(context.Context, *SendEmailRequest, *google_protobuf.Empty) error
	SendInBox(context.Context, *SendInBoxRequest, *google_protobuf.Empty) error
	SendNotify(context.Context, *SendNotifyRequest, *google_protobuf.Empty) error
}

func RegisterNotifyHandler(s server.Server, hdlr NotifyHandler, opts ...server.HandlerOption) error {
	type notify interface {
		SendEmail(ctx context.Context, in *SendEmailRequest, out *google_protobuf.Empty) error
		SendInBox(ctx context.Context, in *SendInBoxRequest, out *google_protobuf.Empty) error
		SendNotify(ctx context.Context, in *SendNotifyRequest, out *google_protobuf.Empty) error
	}
	type Notify struct {
		notify
	}
	h := &notifyHandler{hdlr}
	return s.Handle(s.NewHandler(&Notify{h}, opts...))
}

type notifyHandler struct {
	NotifyHandler
}

func (h *notifyHandler) SendEmail(ctx context.Context, in *SendEmailRequest, out *google_protobuf.Empty) error {
	return h.NotifyHandler.SendEmail(ctx, in, out)
}

func (h *notifyHandler) SendInBox(ctx context.Context, in *SendInBoxRequest, out *google_protobuf.Empty) error {
	return h.NotifyHandler.SendInBox(ctx, in, out)
}

func (h *notifyHandler) SendNotify(ctx context.Context, in *SendNotifyRequest, out *google_protobuf.Empty) error {
	return h.NotifyHandler.SendNotify(ctx, in, out)
}
