apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "teddy.apis.uaa.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "teddy.apis.uaa.name" . }}
    helm.sh/chart: {{ include "teddy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "teddy.apis.uaa.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "teddy.apis.uaa.name" . }}
    helm.sh/chart: {{ include "teddy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ default "ClusterIP" .Values.apis.uaa.type }}
  ports:
    - port: 8083
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "teddy.apis.uaa.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "teddy.apis.uaa.name" . }}-config
data:
  config.yaml: |
    server:
      address: 0.0.0.0
      port: 8083
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "teddy.apis.uaa.name" . }}-secret
type: Opaque
stringData:
  JWTPkcs8: |-
    -----BEGIN PRIVATE KEY-----
    MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDk6+ozDV9z2CZb
    YE5sHCkint7a+SpOQzfhYnNcRXeFA7TyI+0oH22pNi0Obo+uWbCI+pbo48W+teZl
    64doD+L7Q/qz/KYuWnaDpVW5K+FRLmxIKDL+nmd62fQr1wqdzBeHG/u4YPmv/P4q
    LGLnq2Wt+STUFVBNUL45noiYHzhtn4o/NoW2XQzYgrnqbrK+EDJKUWlQ4qdpID6d
    bpvHw5kYFhd9lgT45ZtyIHOrGwwRHm3SP+2eAn0zAavWq/AWFuycY0uGE9eNBbh4
    BiKuNf5OfEFf48PM5unG3l4YhHMeNHBiE6DuigCDP9JV01dw369SzylG6BuV9+uU
    e6ssxkQ/AgMBAAECggEAT98IHbviu/aEm4kkk4/Xwl6P/vLEkf3d92N0QJN0OhKr
    BXkHe+JLTqi6W7izpO9iKsjT8nnWOs4YjyL4YZR5a5WyWS4jhTTG+POszyjCOqLp
    4Ns1v6ThEfoNuWYULC5TXy6iSxh6xa6Nt4U5FP+2QFcXRHATToaHeG8Z1Ym/FG/W
    vlxyeeWBttQPqEYxydJ+reHUvpYl0w/hVgmBG9R2WHuKCs+Y0zbfoDdbJtWPwwKu
    hZxsUxqbgbfr6NMl+e9eZCauxZ2FPSgYCYkm7sCz8u7Wk1IP76ZEQ9vS+9ks/ACy
    GbukEVuY40YTy/LP7YzbG5sOVf1NxMl/QWLXTQwLsQKBgQD4Y1O/rltwxk/NCCsb
    wdoYgC+J30Cw4LQizBBrNhpx9R8K95LyRT+NUvRycgAvDbPyNjP4P15GBNlc1LWs
    AAWfbjlRgXFdPxHgyxHhVwvgwCsBNrTkIeIelADpUvqcpxeU9A8YT92277HrFBVl
    GZ8mis67OL/VhULdajSd9ow4iwKBgQDr794yRF+c35jYXqCJFHr4iMQuNj2q7R6Q
    JEYJ/wZX9iOOlzwnEZskJIMuaBipjTrFrUFLmp4NFLoxOAZyJ8lVBc2DNNcFR6VH
    xU10/5LgaMfc67Y3FkVZUKT/iMn6xVRGRr8IggQPA2kaOBtdWEuzQJ81GjrzZT4i
    cRmoHcKlnQKBgEzxD8dHrmGfvKaJijj98p42TwOJWZOw93vz9H4Rc12rjaMrD6Tm
    mIohkUFGWRI6T2yPJ8gVcRGFfQOJjIEsPJGnZi/+ReyZleMpZG+GNFK5lFi65ovo
    hw/rzuB36NPP2rk0ZNymGMsLMvTb8siviCI7S1CpgpsUvaKyvHvWHJeDAoGANrw7
    LCY4mEg3SVsKm0KpFKeF+8KRo+nGwWHo7cDAU//CV/418kpfV48w778umYcuL1X2
    Y/fG2voICAsbU7hvOM5T0zCbAZqReYkIYzA3fuBQHayBZV5BUGspHC87zHWjC3q2
    Lt8a2fDMnUyO7KTjSv6e8M7ZBkZil9LtRNdCpPECgYAkkP/u7yqI1/fyfij1EJW4
    XFcZMYfFP7LHVIKU8b4hfzJmDBjD4t/7zC2dzYYxmUTQXB4o8gOWhauBOV2qVa7L
    zL5vu2PbU2Pbwc2yZsVio245oYU6xAVnZJ7Xlr/2WNa7dULiLYyZCMH944ljYASJ
    r0mQwY8VRGvzT8HRC33OMw==
    -----END PRIVATE KEY-----
{{- $root := . -}}
{{- with .Values.apis.uaa }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "teddy.apis.uaa.name" $root }}
  labels:
    app.kubernetes.io/name: {{ include "teddy.apis.uaa.name" $root }}
    helm.sh/chart: {{ include "teddy.chart" $root }}
    app.kubernetes.io/instance: {{ $root.Release.Name }}
    app.kubernetes.io/managed-by: {{ $root.Release.Service }}
    app.kubernetes.io/version: {{ .version }}
spec:
  replicas: {{ default 1 $root.Values.apis.uaa.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "teddy.apis.uaa.name" $root }}
      app.kubernetes.io/instance: {{ $root.Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "teddy.apis.uaa.name" $root }}
        app.kubernetes.io/instance: {{ $root.Release.Name }}
    spec:
      serviceAccountName: {{ include "teddy.apis.uaa.name" $root }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "teddy.apis.uaa.name" $root }}-config
        - name: secret-volume
          secret:
            secretName: {{ include "teddy.apis.uaa.name" $root }}-secret
      containers:
        - name: {{ include "teddy.apis.uaa.name" $root }}
          image: "{{ .deploy.image.repository }}"
          imagePullPolicy: {{ .deploy.image.pullPolicy }}
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
            - name: secret-volume
              mountPath: /app/secret
          ports:
            - name: http
              containerPort: 8083
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 8183
          readinessProbe:
            httpGet:
              path: /
              port: 8183
          resources:
{{ toYaml .deploy.resources | indent 12 }}
{{- with .deploy.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .deploy.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .deploy.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
{{- end }}
