[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.6"

[[constraint]]
  name = "github.com/mongodb/mongo-go-driver"
  version = "0.0.18"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.2.0"
