// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/zhsyourai/teddy-backend/common/proto/content/content.proto

package content

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Sort struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Asc                  bool     `protobuf:"varint,2,opt,name=asc,proto3" json:"asc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sort) Reset()         { *m = Sort{} }
func (m *Sort) String() string { return proto.CompactTextString(m) }
func (*Sort) ProtoMessage()    {}
func (*Sort) Descriptor() ([]byte, []int) {
	return fileDescriptor_content_14c3d90b04e7be7b, []int{0}
}
func (m *Sort) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sort.Unmarshal(m, b)
}
func (m *Sort) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sort.Marshal(b, m, deterministic)
}
func (dst *Sort) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sort.Merge(dst, src)
}
func (m *Sort) XXX_Size() int {
	return xxx_messageInfo_Sort.Size(m)
}
func (m *Sort) XXX_DiscardUnknown() {
	xxx_messageInfo_Sort.DiscardUnknown(m)
}

var xxx_messageInfo_Sort proto.InternalMessageInfo

func (m *Sort) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Sort) GetAsc() bool {
	if m != nil {
		return m.Asc
	}
	return false
}

type Tag struct {
	Tag                  string               `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Type                 string               `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Usage                uint64               `protobuf:"varint,3,opt,name=usage,proto3" json:"usage,omitempty"`
	CreateTime           *timestamp.Timestamp `protobuf:"bytes,4,opt,name=createTime,proto3" json:"createTime,omitempty"`
	LastUseTime          *timestamp.Timestamp `protobuf:"bytes,5,opt,name=lastUseTime,proto3" json:"lastUseTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Tag) Reset()         { *m = Tag{} }
func (m *Tag) String() string { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()    {}
func (*Tag) Descriptor() ([]byte, []int) {
	return fileDescriptor_content_14c3d90b04e7be7b, []int{1}
}
func (m *Tag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tag.Unmarshal(m, b)
}
func (m *Tag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tag.Marshal(b, m, deterministic)
}
func (dst *Tag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tag.Merge(dst, src)
}
func (m *Tag) XXX_Size() int {
	return xxx_messageInfo_Tag.Size(m)
}
func (m *Tag) XXX_DiscardUnknown() {
	xxx_messageInfo_Tag.DiscardUnknown(m)
}

var xxx_messageInfo_Tag proto.InternalMessageInfo

func (m *Tag) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *Tag) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Tag) GetUsage() uint64 {
	if m != nil {
		return m.Usage
	}
	return 0
}

func (m *Tag) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *Tag) GetLastUseTime() *timestamp.Timestamp {
	if m != nil {
		return m.LastUseTime
	}
	return nil
}

type TagAndType struct {
	Tag                  string   `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TagAndType) Reset()         { *m = TagAndType{} }
func (m *TagAndType) String() string { return proto.CompactTextString(m) }
func (*TagAndType) ProtoMessage()    {}
func (*TagAndType) Descriptor() ([]byte, []int) {
	return fileDescriptor_content_14c3d90b04e7be7b, []int{2}
}
func (m *TagAndType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TagAndType.Unmarshal(m, b)
}
func (m *TagAndType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TagAndType.Marshal(b, m, deterministic)
}
func (dst *TagAndType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TagAndType.Merge(dst, src)
}
func (m *TagAndType) XXX_Size() int {
	return xxx_messageInfo_TagAndType.Size(m)
}
func (m *TagAndType) XXX_DiscardUnknown() {
	xxx_messageInfo_TagAndType.DiscardUnknown(m)
}

var xxx_messageInfo_TagAndType proto.InternalMessageInfo

func (m *TagAndType) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *TagAndType) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type Info struct {
	InfoID               string               `protobuf:"bytes,1,opt,name=infoID,proto3" json:"infoID,omitempty"`
	Uid                  string               `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Author               string               `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Title                string               `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Summary              string               `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	Country              string               `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"`
	ContentTime          *timestamp.Timestamp `protobuf:"bytes,7,opt,name=contentTime,proto3" json:"contentTime,omitempty"`
	CoverResources       map[string]string    `protobuf:"bytes,8,rep,name=coverResources,proto3" json:"coverResources,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	PublishTime          *timestamp.Timestamp `protobuf:"bytes,9,opt,name=publishTime,proto3" json:"publishTime,omitempty"`
	LastReviewTime       *timestamp.Timestamp `protobuf:"bytes,10,opt,name=lastReviewTime,proto3" json:"lastReviewTime,omitempty"`
	WatchCount           int64                `protobuf:"varint,11,opt,name=watchCount,proto3" json:"watchCount,omitempty"`
	Tags                 []*TagAndType        `protobuf:"bytes,12,rep,name=tags,proto3" json:"tags,omitempty"`
	ThumbUp              int64                `protobuf:"varint,13,opt,name=thumbUp,proto3" json:"thumbUp,omitempty"`
	IsThumbUp            bool                 `protobuf:"varint,14,opt,name=isThumbUp,proto3" json:"isThumbUp,omitempty"`
	ThumbUpList          []string             `protobuf:"bytes,15,rep,name=thumbUpList,proto3" json:"thumbUpList,omitempty"`
	ThumbDown            int64                `protobuf:"varint,16,opt,name=thumbDown,proto3" json:"thumbDown,omitempty"`
	IsThumbDown          bool                 `protobuf:"varint,17,opt,name=isThumbDown,proto3" json:"isThumbDown,omitempty"`
	ThumbDownList        []string             `protobuf:"bytes,18,rep,name=thumbDownList,proto3" json:"thumbDownList,omitempty"`
	Favorites            int64                `protobuf:"varint,19,opt,name=favorites,proto3" json:"favorites,omitempty"`
	IsFavorite           bool                 `protobuf:"varint,20,opt,name=isFavorite,proto3" json:"isFavorite,omitempty"`
	FavoriteList         []string             `protobuf:"bytes,21,rep,name=favoriteList,proto3" json:"favoriteList,omitempty"`
	LastModifyTime       *timestamp.Timestamp `protobuf:"bytes,22,opt,name=lastModifyTime,proto3" json:"lastModifyTime,omitempty"`
	CanReview            bool                 `protobuf:"varint,23,opt,name=canReview,proto3" json:"canReview,omitempty"`
	Valid                bool                 `protobuf:"varint,24,opt,name=valid,proto3" json:"valid,omitempty"`
	Archived             bool                 `protobuf:"varint,25,opt,name=archived,proto3" json:"archived,omitempty"`
	LatestSegmentID      string               `protobuf:"bytes,26,opt,name=LatestSegmentID,proto3" json:"LatestSegmentID,omitempty"`
	SegmentCount         int64                `protobuf:"varint,27,opt,name=SegmentCount,proto3" json:"SegmentCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Info) Reset()         { *m = Info{} }
func (m *Info) String() string { return proto.CompactTextString(m) }
func (*Info) ProtoMessage()    {}
func (*Info) Descriptor() ([]byte, []int) {
	return fileDescriptor_content_14c3d90b04e7be7b, []int{3}
}
func (m *Info) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Info.Unmarshal(m, b)
}
func (m *Info) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Info.Marshal(b, m, deterministic)
}
func (dst *Info) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Info.Merge(dst, src)
}
func (m *Info) XXX_Size() int {
	return xxx_messageInfo_Info.Size(m)
}
func (m *Info) XXX_DiscardUnknown() {
	xxx_messageInfo_Info.DiscardUnknown(m)
}

var xxx_messageInfo_Info proto.InternalMessageInfo

func (m *Info) GetInfoID() string {
	if m != nil {
		return m.InfoID
	}
	return ""
}

func (m *Info) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *Info) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *Info) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Info) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

func (m *Info) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Info) GetContentTime() *timestamp.Timestamp {
	if m != nil {
		return m.ContentTime
	}
	return nil
}

func (m *Info) GetCoverResources() map[string]string {
	if m != nil {
		return m.CoverResources
	}
	return nil
}

func (m *Info) GetPublishTime() *timestamp.Timestamp {
	if m != nil {
		return m.PublishTime
	}
	return nil
}

func (m *Info) GetLastReviewTime() *timestamp.Timestamp {
	if m != nil {
		return m.LastReviewTime
	}
	return nil
}

func (m *Info) GetWatchCount() int64 {
	if m != nil {
		return m.WatchCount
	}
	return 0
}

func (m *Info) GetTags() []*TagAndType {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Info) GetThumbUp() int64 {
	if m != nil {
		return m.ThumbUp
	}
	return 0
}

func (m *Info) GetIsThumbUp() bool {
	if m != nil {
		return m.IsThumbUp
	}
	return false
}

func (m *Info) GetThumbUpList() []string {
	if m != nil {
		return m.ThumbUpList
	}
	return nil
}

func (m *Info) GetThumbDown() int64 {
	if m != nil {
		return m.ThumbDown
	}
	return 0
}

func (m *Info) GetIsThumbDown() bool {
	if m != nil {
		return m.IsThumbDown
	}
	return false
}

func (m *Info) GetThumbDownList() []string {
	if m != nil {
		return m.ThumbDownList
	}
	return nil
}

func (m *Info) GetFavorites() int64 {
	if m != nil {
		return m.Favorites
	}
	return 0
}

func (m *Info) GetIsFavorite() bool {
	if m != nil {
		return m.IsFavorite
	}
	return false
}

func (m *Info) GetFavoriteList() []string {
	if m != nil {
		return m.FavoriteList
	}
	return nil
}

func (m *Info) GetLastModifyTime() *timestamp.Timestamp {
	if m != nil {
		return m.LastModifyTime
	}
	return nil
}

func (m *Info) GetCanReview() bool {
	if m != nil {
		return m.CanReview
	}
	return false
}

func (m *Info) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *Info) GetArchived() bool {
	if m != nil {
		return m.Archived
	}
	return false
}

func (m *Info) GetLatestSegmentID() string {
	if m != nil {
		return m.LatestSegmentID
	}
	return ""
}

func (m *Info) GetSegmentCount() int64 {
	if m != nil {
		return m.SegmentCount
	}
	return 0
}

type Segment struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	InfoID               string            `protobuf:"bytes,2,opt,name=infoID,proto3" json:"infoID,omitempty"`
	No                   int64             `protobuf:"varint,3,opt,name=no,proto3" json:"no,omitempty"`
	Title                string            `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Labels               []string          `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty"`
	Content              map[string]string `protobuf:"bytes,6,rep,name=content,proto3" json:"content,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Segment) Reset()         { *m = Segment{} }
func (m *Segment) String() string { return proto.CompactTextString(m) }
func (*Segment) ProtoMessage()    {}
func (*Segment) Descriptor() ([]byte, []int) {
	return fileDescriptor_content_14c3d90b04e7be7b, []int{4}
}
func (m *Segment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Segment.Unmarshal(m, b)
}
func (m *Segment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Segment.Marshal(b, m, deterministic)
}
func (dst *Segment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Segment.Merge(dst, src)
}
func (m *Segment) XXX_Size() int {
	return xxx_messageInfo_Segment.Size(m)
}
func (m *Segment) XXX_DiscardUnknown() {
	xxx_messageInfo_Segment.DiscardUnknown(m)
}

var xxx_messageInfo_Segment proto.InternalMessageInfo

func (m *Segment) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Segment) GetInfoID() string {
	if m != nil {
		return m.InfoID
	}
	return ""
}

func (m *Segment) GetNo() int64 {
	if m != nil {
		return m.No
	}
	return 0
}

func (m *Segment) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Segment) GetLabels() []string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *Segment) GetContent() map[string]string {
	if m != nil {
		return m.Content
	}
	return nil
}

type GetTagReq struct {
	Page                 uint32   `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size                 uint32   `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Sorts                []*Sort  `protobuf:"bytes,4,rep,name=sorts,proto3" json:"sorts,omitempty"`
	Uid                  string   `protobuf:"bytes,5,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTagReq) Reset()         { *m = GetTagReq{} }
func (m *GetTagReq) String() string { return proto.CompactTextString(m) }
func (*GetTagReq) ProtoMessage()    {}
func (*GetTagReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_content_14c3d90b04e7be7b, []int{5}
}
func (m *GetTagReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTagReq.Unmarshal(m, b)
}
func (m *GetTagReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTagReq.Marshal(b, m, deterministic)
}
func (dst *GetTagReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTagReq.Merge(dst, src)
}
func (m *GetTagReq) XXX_Size() int {
	return xxx_messageInfo_GetTagReq.Size(m)
}
func (m *GetTagReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTagReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetTagReq proto.InternalMessageInfo

func (m *GetTagReq) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetTagReq) GetSize() uint32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *GetTagReq) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *GetTagReq) GetSorts() []*Sort {
	if m != nil {
		return m.Sorts
	}
	return nil
}

func (m *GetTagReq) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type UIDPageReq struct {
	Page                 uint32   `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size                 uint32   `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Sorts                []*Sort  `protobuf:"bytes,3,rep,name=sorts,proto3" json:"sorts,omitempty"`
	Uid                  string   `protobuf:"bytes,4,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UIDPageReq) Reset()         { *m = UIDPageReq{} }
func (m *UIDPageReq) String() string { return proto.CompactTextString(m) }
func (*UIDPageReq) ProtoMessage()    {}
func (*UIDPageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_content_14c3d90b04e7be7b, []int{6}
}
func (m *UIDPageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UIDPageReq.Unmarshal(m, b)
}
func (m *UIDPageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UIDPageReq.Marshal(b, m, deterministic)
}
func (dst *UIDPageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UIDPageReq.Merge(dst, src)
}
func (m *UIDPageReq) XXX_Size() int {
	return xxx_messageInfo_UIDPageReq.Size(m)
}
func (m *UIDPageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UIDPageReq.DiscardUnknown(m)
}

var xxx_messageInfo_UIDPageReq proto.InternalMessageInfo

func (m *UIDPageReq) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *UIDPageReq) GetSize() uint32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *UIDPageReq) GetSorts() []*Sort {
	if m != nil {
		return m.Sorts
	}
	return nil
}

func (m *UIDPageReq) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type GetTagsResp struct {
	Tags                 []*Tag   `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTagsResp) Reset()         { *m = GetTagsResp{} }
func (m *GetTagsResp) String() string { return proto.CompactTextString(m) }
func (*GetTagsResp) ProtoMessage()    {}
func (*GetTagsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_content_14c3d90b04e7be7b, []int{7}
}
func (m *GetTagsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTagsResp.Unmarshal(m, b)
}
func (m *GetTagsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTagsResp.Marshal(b, m, deterministic)
}
func (dst *GetTagsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTagsResp.Merge(dst, src)
}
func (m *GetTagsResp) XXX_Size() int {
	return xxx_messageInfo_GetTagsResp.Size(m)
}
func (m *GetTagsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTagsResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetTagsResp proto.InternalMessageInfo

func (m *GetTagsResp) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

type PublishInfoReq struct {
	Uid                  string            `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Author               string            `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Title                string            `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Summary              string            `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	Country              string            `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	Tags                 []*TagAndType     `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	CoverResources       map[string]string `protobuf:"bytes,7,rep,name=coverResources,proto3" json:"coverResources,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CanReview            bool              `protobuf:"varint,8,opt,name=canReview,proto3" json:"canReview,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PublishInfoReq) Reset()         { *m = PublishInfoReq{} }
func (m *PublishInfoReq) String() string { return proto.CompactTextString(m) }
func (*PublishInfoReq) ProtoMessage()    {}
func (*PublishInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_content_14c3d90b04e7be7b, []int{8}
}
func (m *PublishInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishInfoReq.Unmarshal(m, b)
}
func (m *PublishInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishInfoReq.Marshal(b, m, deterministic)
}
func (dst *PublishInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishInfoReq.Merge(dst, src)
}
func (m *PublishInfoReq) XXX_Size() int {
	return xxx_messageInfo_PublishInfoReq.Size(m)
}
func (m *PublishInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_PublishInfoReq proto.InternalMessageInfo

func (m *PublishInfoReq) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *PublishInfoReq) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *PublishInfoReq) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *PublishInfoReq) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

func (m *PublishInfoReq) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *PublishInfoReq) GetTags() []*TagAndType {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *PublishInfoReq) GetCoverResources() map[string]string {
	if m != nil {
		return m.CoverResources
	}
	return nil
}

func (m *PublishInfoReq) GetCanReview() bool {
	if m != nil {
		return m.CanReview
	}
	return false
}

type EditInfoReq struct {
	InfoID               string            `protobuf:"bytes,1,opt,name=infoID,proto3" json:"infoID,omitempty"`
	Uid                  string            `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Author               string            `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Title                string            `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Summary              string            `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	Country              string            `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"`
	Tags                 []*TagAndType     `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	CoverResources       map[string]string `protobuf:"bytes,8,rep,name=coverResources,proto3" json:"coverResources,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CanReview            bool              `protobuf:"varint,9,opt,name=canReview,proto3" json:"canReview,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *EditInfoReq) Reset()         { *m = EditInfoReq{} }
func (m *EditInfoReq) String() string { return proto.CompactTextString(m) }
func (*EditInfoReq) ProtoMessage()    {}
func (*EditInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_content_14c3d90b04e7be7b, []int{9}
}
func (m *EditInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditInfoReq.Unmarshal(m, b)
}
func (m *EditInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditInfoReq.Marshal(b, m, deterministic)
}
func (dst *EditInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditInfoReq.Merge(dst, src)
}
func (m *EditInfoReq) XXX_Size() int {
	return xxx_messageInfo_EditInfoReq.Size(m)
}
func (m *EditInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_EditInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_EditInfoReq proto.InternalMessageInfo

func (m *EditInfoReq) GetInfoID() string {
	if m != nil {
		return m.InfoID
	}
	return ""
}

func (m *EditInfoReq) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *EditInfoReq) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *EditInfoReq) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *EditInfoReq) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

func (m *EditInfoReq) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *EditInfoReq) GetTags() []*TagAndType {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *EditInfoReq) GetCoverResources() map[string]string {
	if m != nil {
		return m.CoverResources
	}
	return nil
}

func (m *EditInfoReq) GetCanReview() bool {
	if m != nil {
		return m.CanReview
	}
	return false
}

type GetSegmentsReq struct {
	Page                 uint32   `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size                 uint32   `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	InfoID               string   `protobuf:"bytes,3,opt,name=infoID,proto3" json:"infoID,omitempty"`
	Uid                  string   `protobuf:"bytes,4,opt,name=uid,proto3" json:"uid,omitempty"`
	Labels               []string `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty"`
	Sorts                []*Sort  `protobuf:"bytes,6,rep,name=sorts,proto3" json:"sorts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSegmentsReq) Reset()         { *m = GetSegmentsReq{} }
func (m *GetSegmentsReq) String() string { return proto.CompactTextString(m) }
func (*GetSegmentsReq) ProtoMessage()    {}
func (*GetSegmentsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_content_14c3d90b04e7be7b, []int{10}
}
func (m *GetSegmentsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSegmentsReq.Unmarshal(m, b)
}
func (m *GetSegmentsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSegmentsReq.Marshal(b, m, deterministic)
}
func (dst *GetSegmentsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSegmentsReq.Merge(dst, src)
}
func (m *GetSegmentsReq) XXX_Size() int {
	return xxx_messageInfo_GetSegmentsReq.Size(m)
}
func (m *GetSegmentsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSegmentsReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetSegmentsReq proto.InternalMessageInfo

func (m *GetSegmentsReq) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetSegmentsReq) GetSize() uint32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *GetSegmentsReq) GetInfoID() string {
	if m != nil {
		return m.InfoID
	}
	return ""
}

func (m *GetSegmentsReq) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *GetSegmentsReq) GetLabels() []string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *GetSegmentsReq) GetSorts() []*Sort {
	if m != nil {
		return m.Sorts
	}
	return nil
}

type Segments struct {
	Segments             []*Segment `protobuf:"bytes,1,rep,name=segments,proto3" json:"segments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Segments) Reset()         { *m = Segments{} }
func (m *Segments) String() string { return proto.CompactTextString(m) }
func (*Segments) ProtoMessage()    {}
func (*Segments) Descriptor() ([]byte, []int) {
	return fileDescriptor_content_14c3d90b04e7be7b, []int{11}
}
func (m *Segments) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Segments.Unmarshal(m, b)
}
func (m *Segments) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Segments.Marshal(b, m, deterministic)
}
func (dst *Segments) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Segments.Merge(dst, src)
}
func (m *Segments) XXX_Size() int {
	return xxx_messageInfo_Segments.Size(m)
}
func (m *Segments) XXX_DiscardUnknown() {
	xxx_messageInfo_Segments.DiscardUnknown(m)
}

var xxx_messageInfo_Segments proto.InternalMessageInfo

func (m *Segments) GetSegments() []*Segment {
	if m != nil {
		return m.Segments
	}
	return nil
}

type PublishSegmentReq struct {
	InfoID               string            `protobuf:"bytes,1,opt,name=infoID,proto3" json:"infoID,omitempty"`
	Uid                  string            `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	No                   int64             `protobuf:"varint,3,opt,name=no,proto3" json:"no,omitempty"`
	Title                string            `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Labels               []string          `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty"`
	Content              map[string]string `protobuf:"bytes,6,rep,name=content,proto3" json:"content,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PublishSegmentReq) Reset()         { *m = PublishSegmentReq{} }
func (m *PublishSegmentReq) String() string { return proto.CompactTextString(m) }
func (*PublishSegmentReq) ProtoMessage()    {}
func (*PublishSegmentReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_content_14c3d90b04e7be7b, []int{12}
}
func (m *PublishSegmentReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishSegmentReq.Unmarshal(m, b)
}
func (m *PublishSegmentReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishSegmentReq.Marshal(b, m, deterministic)
}
func (dst *PublishSegmentReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishSegmentReq.Merge(dst, src)
}
func (m *PublishSegmentReq) XXX_Size() int {
	return xxx_messageInfo_PublishSegmentReq.Size(m)
}
func (m *PublishSegmentReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishSegmentReq.DiscardUnknown(m)
}

var xxx_messageInfo_PublishSegmentReq proto.InternalMessageInfo

func (m *PublishSegmentReq) GetInfoID() string {
	if m != nil {
		return m.InfoID
	}
	return ""
}

func (m *PublishSegmentReq) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *PublishSegmentReq) GetNo() int64 {
	if m != nil {
		return m.No
	}
	return 0
}

func (m *PublishSegmentReq) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *PublishSegmentReq) GetLabels() []string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *PublishSegmentReq) GetContent() map[string]string {
	if m != nil {
		return m.Content
	}
	return nil
}

type EditSegmentReq struct {
	InfoID               string            `protobuf:"bytes,1,opt,name=infoID,proto3" json:"infoID,omitempty"`
	Uid                  string            `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	SegID                string            `protobuf:"bytes,3,opt,name=segID,proto3" json:"segID,omitempty"`
	No                   int64             `protobuf:"varint,4,opt,name=no,proto3" json:"no,omitempty"`
	Title                string            `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Labels               []string          `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty"`
	Content              map[string]string `protobuf:"bytes,7,rep,name=content,proto3" json:"content,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *EditSegmentReq) Reset()         { *m = EditSegmentReq{} }
func (m *EditSegmentReq) String() string { return proto.CompactTextString(m) }
func (*EditSegmentReq) ProtoMessage()    {}
func (*EditSegmentReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_content_14c3d90b04e7be7b, []int{13}
}
func (m *EditSegmentReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditSegmentReq.Unmarshal(m, b)
}
func (m *EditSegmentReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditSegmentReq.Marshal(b, m, deterministic)
}
func (dst *EditSegmentReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditSegmentReq.Merge(dst, src)
}
func (m *EditSegmentReq) XXX_Size() int {
	return xxx_messageInfo_EditSegmentReq.Size(m)
}
func (m *EditSegmentReq) XXX_DiscardUnknown() {
	xxx_messageInfo_EditSegmentReq.DiscardUnknown(m)
}

var xxx_messageInfo_EditSegmentReq proto.InternalMessageInfo

func (m *EditSegmentReq) GetInfoID() string {
	if m != nil {
		return m.InfoID
	}
	return ""
}

func (m *EditSegmentReq) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *EditSegmentReq) GetSegID() string {
	if m != nil {
		return m.SegID
	}
	return ""
}

func (m *EditSegmentReq) GetNo() int64 {
	if m != nil {
		return m.No
	}
	return 0
}

func (m *EditSegmentReq) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *EditSegmentReq) GetLabels() []string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *EditSegmentReq) GetContent() map[string]string {
	if m != nil {
		return m.Content
	}
	return nil
}

type InfoIDAndUIDAndSegIDReq struct {
	InfoID               string   `protobuf:"bytes,1,opt,name=infoID,proto3" json:"infoID,omitempty"`
	Uid                  string   `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	SegID                string   `protobuf:"bytes,3,opt,name=segID,proto3" json:"segID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InfoIDAndUIDAndSegIDReq) Reset()         { *m = InfoIDAndUIDAndSegIDReq{} }
func (m *InfoIDAndUIDAndSegIDReq) String() string { return proto.CompactTextString(m) }
func (*InfoIDAndUIDAndSegIDReq) ProtoMessage()    {}
func (*InfoIDAndUIDAndSegIDReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_content_14c3d90b04e7be7b, []int{14}
}
func (m *InfoIDAndUIDAndSegIDReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoIDAndUIDAndSegIDReq.Unmarshal(m, b)
}
func (m *InfoIDAndUIDAndSegIDReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoIDAndUIDAndSegIDReq.Marshal(b, m, deterministic)
}
func (dst *InfoIDAndUIDAndSegIDReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoIDAndUIDAndSegIDReq.Merge(dst, src)
}
func (m *InfoIDAndUIDAndSegIDReq) XXX_Size() int {
	return xxx_messageInfo_InfoIDAndUIDAndSegIDReq.Size(m)
}
func (m *InfoIDAndUIDAndSegIDReq) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoIDAndUIDAndSegIDReq.DiscardUnknown(m)
}

var xxx_messageInfo_InfoIDAndUIDAndSegIDReq proto.InternalMessageInfo

func (m *InfoIDAndUIDAndSegIDReq) GetInfoID() string {
	if m != nil {
		return m.InfoID
	}
	return ""
}

func (m *InfoIDAndUIDAndSegIDReq) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *InfoIDAndUIDAndSegIDReq) GetSegID() string {
	if m != nil {
		return m.SegID
	}
	return ""
}

type GetInfoReq struct {
	InfoID               string   `protobuf:"bytes,1,opt,name=infoID,proto3" json:"infoID,omitempty"`
	Uid                  string   `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInfoReq) Reset()         { *m = GetInfoReq{} }
func (m *GetInfoReq) String() string { return proto.CompactTextString(m) }
func (*GetInfoReq) ProtoMessage()    {}
func (*GetInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_content_14c3d90b04e7be7b, []int{15}
}
func (m *GetInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfoReq.Unmarshal(m, b)
}
func (m *GetInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfoReq.Marshal(b, m, deterministic)
}
func (dst *GetInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfoReq.Merge(dst, src)
}
func (m *GetInfoReq) XXX_Size() int {
	return xxx_messageInfo_GetInfoReq.Size(m)
}
func (m *GetInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfoReq proto.InternalMessageInfo

func (m *GetInfoReq) GetInfoID() string {
	if m != nil {
		return m.InfoID
	}
	return ""
}

func (m *GetInfoReq) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type GetInfosReq struct {
	Page                 uint32        `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size                 uint32        `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Sorts                []*Sort       `protobuf:"bytes,3,rep,name=sorts,proto3" json:"sorts,omitempty"`
	Uid                  string        `protobuf:"bytes,4,opt,name=uid,proto3" json:"uid,omitempty"`
	Title                string        `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Tags                 []*TagAndType `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetInfosReq) Reset()         { *m = GetInfosReq{} }
func (m *GetInfosReq) String() string { return proto.CompactTextString(m) }
func (*GetInfosReq) ProtoMessage()    {}
func (*GetInfosReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_content_14c3d90b04e7be7b, []int{16}
}
func (m *GetInfosReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfosReq.Unmarshal(m, b)
}
func (m *GetInfosReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfosReq.Marshal(b, m, deterministic)
}
func (dst *GetInfosReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfosReq.Merge(dst, src)
}
func (m *GetInfosReq) XXX_Size() int {
	return xxx_messageInfo_GetInfosReq.Size(m)
}
func (m *GetInfosReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfosReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfosReq proto.InternalMessageInfo

func (m *GetInfosReq) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetInfosReq) GetSize() uint32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *GetInfosReq) GetSorts() []*Sort {
	if m != nil {
		return m.Sorts
	}
	return nil
}

func (m *GetInfosReq) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *GetInfosReq) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *GetInfosReq) GetTags() []*TagAndType {
	if m != nil {
		return m.Tags
	}
	return nil
}

type GetInfosResp struct {
	Infos                []*Info  `protobuf:"bytes,1,rep,name=infos,proto3" json:"infos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInfosResp) Reset()         { *m = GetInfosResp{} }
func (m *GetInfosResp) String() string { return proto.CompactTextString(m) }
func (*GetInfosResp) ProtoMessage()    {}
func (*GetInfosResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_content_14c3d90b04e7be7b, []int{17}
}
func (m *GetInfosResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfosResp.Unmarshal(m, b)
}
func (m *GetInfosResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfosResp.Marshal(b, m, deterministic)
}
func (dst *GetInfosResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfosResp.Merge(dst, src)
}
func (m *GetInfosResp) XXX_Size() int {
	return xxx_messageInfo_GetInfosResp.Size(m)
}
func (m *GetInfosResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfosResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfosResp proto.InternalMessageInfo

func (m *GetInfosResp) GetInfos() []*Info {
	if m != nil {
		return m.Infos
	}
	return nil
}

type InfoIDAndUIDReq struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	InfoID               string   `protobuf:"bytes,2,opt,name=infoID,proto3" json:"infoID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InfoIDAndUIDReq) Reset()         { *m = InfoIDAndUIDReq{} }
func (m *InfoIDAndUIDReq) String() string { return proto.CompactTextString(m) }
func (*InfoIDAndUIDReq) ProtoMessage()    {}
func (*InfoIDAndUIDReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_content_14c3d90b04e7be7b, []int{18}
}
func (m *InfoIDAndUIDReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoIDAndUIDReq.Unmarshal(m, b)
}
func (m *InfoIDAndUIDReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoIDAndUIDReq.Marshal(b, m, deterministic)
}
func (dst *InfoIDAndUIDReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoIDAndUIDReq.Merge(dst, src)
}
func (m *InfoIDAndUIDReq) XXX_Size() int {
	return xxx_messageInfo_InfoIDAndUIDReq.Size(m)
}
func (m *InfoIDAndUIDReq) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoIDAndUIDReq.DiscardUnknown(m)
}

var xxx_messageInfo_InfoIDAndUIDReq proto.InternalMessageInfo

func (m *InfoIDAndUIDReq) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *InfoIDAndUIDReq) GetInfoID() string {
	if m != nil {
		return m.InfoID
	}
	return ""
}

type InfoIDPageReq struct {
	InfoID               string   `protobuf:"bytes,1,opt,name=infoID,proto3" json:"infoID,omitempty"`
	Page                 uint32   `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size                 uint32   `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Sorts                []*Sort  `protobuf:"bytes,4,rep,name=sorts,proto3" json:"sorts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InfoIDPageReq) Reset()         { *m = InfoIDPageReq{} }
func (m *InfoIDPageReq) String() string { return proto.CompactTextString(m) }
func (*InfoIDPageReq) ProtoMessage()    {}
func (*InfoIDPageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_content_14c3d90b04e7be7b, []int{19}
}
func (m *InfoIDPageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoIDPageReq.Unmarshal(m, b)
}
func (m *InfoIDPageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoIDPageReq.Marshal(b, m, deterministic)
}
func (dst *InfoIDPageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoIDPageReq.Merge(dst, src)
}
func (m *InfoIDPageReq) XXX_Size() int {
	return xxx_messageInfo_InfoIDPageReq.Size(m)
}
func (m *InfoIDPageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoIDPageReq.DiscardUnknown(m)
}

var xxx_messageInfo_InfoIDPageReq proto.InternalMessageInfo

func (m *InfoIDPageReq) GetInfoID() string {
	if m != nil {
		return m.InfoID
	}
	return ""
}

func (m *InfoIDPageReq) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *InfoIDPageReq) GetSize() uint32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *InfoIDPageReq) GetSorts() []*Sort {
	if m != nil {
		return m.Sorts
	}
	return nil
}

type UIDWithTime struct {
	Uid                  string               `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Time                 *timestamp.Timestamp `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UIDWithTime) Reset()         { *m = UIDWithTime{} }
func (m *UIDWithTime) String() string { return proto.CompactTextString(m) }
func (*UIDWithTime) ProtoMessage()    {}
func (*UIDWithTime) Descriptor() ([]byte, []int) {
	return fileDescriptor_content_14c3d90b04e7be7b, []int{20}
}
func (m *UIDWithTime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UIDWithTime.Unmarshal(m, b)
}
func (m *UIDWithTime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UIDWithTime.Marshal(b, m, deterministic)
}
func (dst *UIDWithTime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UIDWithTime.Merge(dst, src)
}
func (m *UIDWithTime) XXX_Size() int {
	return xxx_messageInfo_UIDWithTime.Size(m)
}
func (m *UIDWithTime) XXX_DiscardUnknown() {
	xxx_messageInfo_UIDWithTime.DiscardUnknown(m)
}

var xxx_messageInfo_UIDWithTime proto.InternalMessageInfo

func (m *UIDWithTime) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *UIDWithTime) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

type UserIDsResp struct {
	Items                []*UIDWithTime `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *UserIDsResp) Reset()         { *m = UserIDsResp{} }
func (m *UserIDsResp) String() string { return proto.CompactTextString(m) }
func (*UserIDsResp) ProtoMessage()    {}
func (*UserIDsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_content_14c3d90b04e7be7b, []int{21}
}
func (m *UserIDsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserIDsResp.Unmarshal(m, b)
}
func (m *UserIDsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserIDsResp.Marshal(b, m, deterministic)
}
func (dst *UserIDsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserIDsResp.Merge(dst, src)
}
func (m *UserIDsResp) XXX_Size() int {
	return xxx_messageInfo_UserIDsResp.Size(m)
}
func (m *UserIDsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UserIDsResp.DiscardUnknown(m)
}

var xxx_messageInfo_UserIDsResp proto.InternalMessageInfo

func (m *UserIDsResp) GetItems() []*UIDWithTime {
	if m != nil {
		return m.Items
	}
	return nil
}

type InfoIDWithTime struct {
	InfoId               string               `protobuf:"bytes,1,opt,name=infoId,proto3" json:"infoId,omitempty"`
	Time                 *timestamp.Timestamp `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *InfoIDWithTime) Reset()         { *m = InfoIDWithTime{} }
func (m *InfoIDWithTime) String() string { return proto.CompactTextString(m) }
func (*InfoIDWithTime) ProtoMessage()    {}
func (*InfoIDWithTime) Descriptor() ([]byte, []int) {
	return fileDescriptor_content_14c3d90b04e7be7b, []int{22}
}
func (m *InfoIDWithTime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoIDWithTime.Unmarshal(m, b)
}
func (m *InfoIDWithTime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoIDWithTime.Marshal(b, m, deterministic)
}
func (dst *InfoIDWithTime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoIDWithTime.Merge(dst, src)
}
func (m *InfoIDWithTime) XXX_Size() int {
	return xxx_messageInfo_InfoIDWithTime.Size(m)
}
func (m *InfoIDWithTime) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoIDWithTime.DiscardUnknown(m)
}

var xxx_messageInfo_InfoIDWithTime proto.InternalMessageInfo

func (m *InfoIDWithTime) GetInfoId() string {
	if m != nil {
		return m.InfoId
	}
	return ""
}

func (m *InfoIDWithTime) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

type InfoIDsResp struct {
	Ids                  []*InfoIDWithTime `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *InfoIDsResp) Reset()         { *m = InfoIDsResp{} }
func (m *InfoIDsResp) String() string { return proto.CompactTextString(m) }
func (*InfoIDsResp) ProtoMessage()    {}
func (*InfoIDsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_content_14c3d90b04e7be7b, []int{23}
}
func (m *InfoIDsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoIDsResp.Unmarshal(m, b)
}
func (m *InfoIDsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoIDsResp.Marshal(b, m, deterministic)
}
func (dst *InfoIDsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoIDsResp.Merge(dst, src)
}
func (m *InfoIDsResp) XXX_Size() int {
	return xxx_messageInfo_InfoIDsResp.Size(m)
}
func (m *InfoIDsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoIDsResp.DiscardUnknown(m)
}

var xxx_messageInfo_InfoIDsResp proto.InternalMessageInfo

func (m *InfoIDsResp) GetIds() []*InfoIDWithTime {
	if m != nil {
		return m.Ids
	}
	return nil
}

func init() {
	proto.RegisterType((*Sort)(nil), "teddy.srv.content.Sort")
	proto.RegisterType((*Tag)(nil), "teddy.srv.content.Tag")
	proto.RegisterType((*TagAndType)(nil), "teddy.srv.content.TagAndType")
	proto.RegisterType((*Info)(nil), "teddy.srv.content.Info")
	proto.RegisterMapType((map[string]string)(nil), "teddy.srv.content.Info.CoverResourcesEntry")
	proto.RegisterType((*Segment)(nil), "teddy.srv.content.Segment")
	proto.RegisterMapType((map[string]string)(nil), "teddy.srv.content.Segment.ContentEntry")
	proto.RegisterType((*GetTagReq)(nil), "teddy.srv.content.GetTagReq")
	proto.RegisterType((*UIDPageReq)(nil), "teddy.srv.content.UIDPageReq")
	proto.RegisterType((*GetTagsResp)(nil), "teddy.srv.content.GetTagsResp")
	proto.RegisterType((*PublishInfoReq)(nil), "teddy.srv.content.PublishInfoReq")
	proto.RegisterMapType((map[string]string)(nil), "teddy.srv.content.PublishInfoReq.CoverResourcesEntry")
	proto.RegisterType((*EditInfoReq)(nil), "teddy.srv.content.EditInfoReq")
	proto.RegisterMapType((map[string]string)(nil), "teddy.srv.content.EditInfoReq.CoverResourcesEntry")
	proto.RegisterType((*GetSegmentsReq)(nil), "teddy.srv.content.GetSegmentsReq")
	proto.RegisterType((*Segments)(nil), "teddy.srv.content.Segments")
	proto.RegisterType((*PublishSegmentReq)(nil), "teddy.srv.content.PublishSegmentReq")
	proto.RegisterMapType((map[string]string)(nil), "teddy.srv.content.PublishSegmentReq.ContentEntry")
	proto.RegisterType((*EditSegmentReq)(nil), "teddy.srv.content.EditSegmentReq")
	proto.RegisterMapType((map[string]string)(nil), "teddy.srv.content.EditSegmentReq.ContentEntry")
	proto.RegisterType((*InfoIDAndUIDAndSegIDReq)(nil), "teddy.srv.content.InfoIDAndUIDAndSegIDReq")
	proto.RegisterType((*GetInfoReq)(nil), "teddy.srv.content.GetInfoReq")
	proto.RegisterType((*GetInfosReq)(nil), "teddy.srv.content.GetInfosReq")
	proto.RegisterType((*GetInfosResp)(nil), "teddy.srv.content.GetInfosResp")
	proto.RegisterType((*InfoIDAndUIDReq)(nil), "teddy.srv.content.InfoIDAndUIDReq")
	proto.RegisterType((*InfoIDPageReq)(nil), "teddy.srv.content.InfoIDPageReq")
	proto.RegisterType((*UIDWithTime)(nil), "teddy.srv.content.UIDWithTime")
	proto.RegisterType((*UserIDsResp)(nil), "teddy.srv.content.UserIDsResp")
	proto.RegisterType((*InfoIDWithTime)(nil), "teddy.srv.content.InfoIDWithTime")
	proto.RegisterType((*InfoIDsResp)(nil), "teddy.srv.content.InfoIDsResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ContentClient is the client API for Content service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ContentClient interface {
	GetTags(ctx context.Context, in *GetTagReq, opts ...grpc.CallOption) (*GetTagsResp, error)
	PublishInfo(ctx context.Context, in *PublishInfoReq, opts ...grpc.CallOption) (*empty.Empty, error)
	EditInfo(ctx context.Context, in *EditInfoReq, opts ...grpc.CallOption) (*empty.Empty, error)
	GetInfo(ctx context.Context, in *GetInfoReq, opts ...grpc.CallOption) (*Info, error)
	GetInfos(ctx context.Context, in *GetInfosReq, opts ...grpc.CallOption) (*GetInfosResp, error)
	DeleteInfo(ctx context.Context, in *InfoIDAndUIDReq, opts ...grpc.CallOption) (*empty.Empty, error)
	WatchInfo(ctx context.Context, in *InfoIDAndUIDReq, opts ...grpc.CallOption) (*empty.Empty, error)
	GetSegments(ctx context.Context, in *GetSegmentsReq, opts ...grpc.CallOption) (*Segments, error)
	GetSegment(ctx context.Context, in *InfoIDAndUIDAndSegIDReq, opts ...grpc.CallOption) (*Segment, error)
	PublishSegment(ctx context.Context, in *PublishSegmentReq, opts ...grpc.CallOption) (*empty.Empty, error)
	EditSegment(ctx context.Context, in *EditSegmentReq, opts ...grpc.CallOption) (*empty.Empty, error)
	DeleteSegment(ctx context.Context, in *InfoIDAndUIDAndSegIDReq, opts ...grpc.CallOption) (*empty.Empty, error)
	ThumbUp(ctx context.Context, in *InfoIDAndUIDReq, opts ...grpc.CallOption) (*empty.Empty, error)
	DeleteThumbUp(ctx context.Context, in *InfoIDAndUIDReq, opts ...grpc.CallOption) (*empty.Empty, error)
	GetUserThumbUp(ctx context.Context, in *UIDPageReq, opts ...grpc.CallOption) (*InfoIDsResp, error)
	GetInfoThumbUp(ctx context.Context, in *InfoIDPageReq, opts ...grpc.CallOption) (*UserIDsResp, error)
	ThumbDown(ctx context.Context, in *InfoIDAndUIDReq, opts ...grpc.CallOption) (*empty.Empty, error)
	DeleteThumbDown(ctx context.Context, in *InfoIDAndUIDReq, opts ...grpc.CallOption) (*empty.Empty, error)
	GetUserThumbDown(ctx context.Context, in *UIDPageReq, opts ...grpc.CallOption) (*InfoIDsResp, error)
	GetInfoThumbDown(ctx context.Context, in *InfoIDPageReq, opts ...grpc.CallOption) (*UserIDsResp, error)
	Favorite(ctx context.Context, in *InfoIDAndUIDReq, opts ...grpc.CallOption) (*empty.Empty, error)
	DeleteFavorite(ctx context.Context, in *InfoIDAndUIDReq, opts ...grpc.CallOption) (*empty.Empty, error)
	GetUserFavorite(ctx context.Context, in *UIDPageReq, opts ...grpc.CallOption) (*InfoIDsResp, error)
	GetInfoFavorite(ctx context.Context, in *InfoIDPageReq, opts ...grpc.CallOption) (*UserIDsResp, error)
}

type contentClient struct {
	cc *grpc.ClientConn
}

func NewContentClient(cc *grpc.ClientConn) ContentClient {
	return &contentClient{cc}
}

func (c *contentClient) GetTags(ctx context.Context, in *GetTagReq, opts ...grpc.CallOption) (*GetTagsResp, error) {
	out := new(GetTagsResp)
	err := c.cc.Invoke(ctx, "/teddy.srv.content.Content/GetTags", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentClient) PublishInfo(ctx context.Context, in *PublishInfoReq, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/teddy.srv.content.Content/PublishInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentClient) EditInfo(ctx context.Context, in *EditInfoReq, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/teddy.srv.content.Content/EditInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentClient) GetInfo(ctx context.Context, in *GetInfoReq, opts ...grpc.CallOption) (*Info, error) {
	out := new(Info)
	err := c.cc.Invoke(ctx, "/teddy.srv.content.Content/GetInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentClient) GetInfos(ctx context.Context, in *GetInfosReq, opts ...grpc.CallOption) (*GetInfosResp, error) {
	out := new(GetInfosResp)
	err := c.cc.Invoke(ctx, "/teddy.srv.content.Content/GetInfos", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentClient) DeleteInfo(ctx context.Context, in *InfoIDAndUIDReq, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/teddy.srv.content.Content/DeleteInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentClient) WatchInfo(ctx context.Context, in *InfoIDAndUIDReq, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/teddy.srv.content.Content/WatchInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentClient) GetSegments(ctx context.Context, in *GetSegmentsReq, opts ...grpc.CallOption) (*Segments, error) {
	out := new(Segments)
	err := c.cc.Invoke(ctx, "/teddy.srv.content.Content/GetSegments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentClient) GetSegment(ctx context.Context, in *InfoIDAndUIDAndSegIDReq, opts ...grpc.CallOption) (*Segment, error) {
	out := new(Segment)
	err := c.cc.Invoke(ctx, "/teddy.srv.content.Content/GetSegment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentClient) PublishSegment(ctx context.Context, in *PublishSegmentReq, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/teddy.srv.content.Content/PublishSegment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentClient) EditSegment(ctx context.Context, in *EditSegmentReq, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/teddy.srv.content.Content/EditSegment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentClient) DeleteSegment(ctx context.Context, in *InfoIDAndUIDAndSegIDReq, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/teddy.srv.content.Content/DeleteSegment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentClient) ThumbUp(ctx context.Context, in *InfoIDAndUIDReq, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/teddy.srv.content.Content/ThumbUp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentClient) DeleteThumbUp(ctx context.Context, in *InfoIDAndUIDReq, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/teddy.srv.content.Content/DeleteThumbUp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentClient) GetUserThumbUp(ctx context.Context, in *UIDPageReq, opts ...grpc.CallOption) (*InfoIDsResp, error) {
	out := new(InfoIDsResp)
	err := c.cc.Invoke(ctx, "/teddy.srv.content.Content/GetUserThumbUp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentClient) GetInfoThumbUp(ctx context.Context, in *InfoIDPageReq, opts ...grpc.CallOption) (*UserIDsResp, error) {
	out := new(UserIDsResp)
	err := c.cc.Invoke(ctx, "/teddy.srv.content.Content/GetInfoThumbUp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentClient) ThumbDown(ctx context.Context, in *InfoIDAndUIDReq, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/teddy.srv.content.Content/ThumbDown", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentClient) DeleteThumbDown(ctx context.Context, in *InfoIDAndUIDReq, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/teddy.srv.content.Content/DeleteThumbDown", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentClient) GetUserThumbDown(ctx context.Context, in *UIDPageReq, opts ...grpc.CallOption) (*InfoIDsResp, error) {
	out := new(InfoIDsResp)
	err := c.cc.Invoke(ctx, "/teddy.srv.content.Content/GetUserThumbDown", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentClient) GetInfoThumbDown(ctx context.Context, in *InfoIDPageReq, opts ...grpc.CallOption) (*UserIDsResp, error) {
	out := new(UserIDsResp)
	err := c.cc.Invoke(ctx, "/teddy.srv.content.Content/GetInfoThumbDown", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentClient) Favorite(ctx context.Context, in *InfoIDAndUIDReq, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/teddy.srv.content.Content/Favorite", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentClient) DeleteFavorite(ctx context.Context, in *InfoIDAndUIDReq, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/teddy.srv.content.Content/DeleteFavorite", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentClient) GetUserFavorite(ctx context.Context, in *UIDPageReq, opts ...grpc.CallOption) (*InfoIDsResp, error) {
	out := new(InfoIDsResp)
	err := c.cc.Invoke(ctx, "/teddy.srv.content.Content/GetUserFavorite", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentClient) GetInfoFavorite(ctx context.Context, in *InfoIDPageReq, opts ...grpc.CallOption) (*UserIDsResp, error) {
	out := new(UserIDsResp)
	err := c.cc.Invoke(ctx, "/teddy.srv.content.Content/GetInfoFavorite", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContentServer is the server API for Content service.
type ContentServer interface {
	GetTags(context.Context, *GetTagReq) (*GetTagsResp, error)
	PublishInfo(context.Context, *PublishInfoReq) (*empty.Empty, error)
	EditInfo(context.Context, *EditInfoReq) (*empty.Empty, error)
	GetInfo(context.Context, *GetInfoReq) (*Info, error)
	GetInfos(context.Context, *GetInfosReq) (*GetInfosResp, error)
	DeleteInfo(context.Context, *InfoIDAndUIDReq) (*empty.Empty, error)
	WatchInfo(context.Context, *InfoIDAndUIDReq) (*empty.Empty, error)
	GetSegments(context.Context, *GetSegmentsReq) (*Segments, error)
	GetSegment(context.Context, *InfoIDAndUIDAndSegIDReq) (*Segment, error)
	PublishSegment(context.Context, *PublishSegmentReq) (*empty.Empty, error)
	EditSegment(context.Context, *EditSegmentReq) (*empty.Empty, error)
	DeleteSegment(context.Context, *InfoIDAndUIDAndSegIDReq) (*empty.Empty, error)
	ThumbUp(context.Context, *InfoIDAndUIDReq) (*empty.Empty, error)
	DeleteThumbUp(context.Context, *InfoIDAndUIDReq) (*empty.Empty, error)
	GetUserThumbUp(context.Context, *UIDPageReq) (*InfoIDsResp, error)
	GetInfoThumbUp(context.Context, *InfoIDPageReq) (*UserIDsResp, error)
	ThumbDown(context.Context, *InfoIDAndUIDReq) (*empty.Empty, error)
	DeleteThumbDown(context.Context, *InfoIDAndUIDReq) (*empty.Empty, error)
	GetUserThumbDown(context.Context, *UIDPageReq) (*InfoIDsResp, error)
	GetInfoThumbDown(context.Context, *InfoIDPageReq) (*UserIDsResp, error)
	Favorite(context.Context, *InfoIDAndUIDReq) (*empty.Empty, error)
	DeleteFavorite(context.Context, *InfoIDAndUIDReq) (*empty.Empty, error)
	GetUserFavorite(context.Context, *UIDPageReq) (*InfoIDsResp, error)
	GetInfoFavorite(context.Context, *InfoIDPageReq) (*UserIDsResp, error)
}

func RegisterContentServer(s *grpc.Server, srv ContentServer) {
	s.RegisterService(&_Content_serviceDesc, srv)
}

func _Content_GetTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTagReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServer).GetTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/teddy.srv.content.Content/GetTags",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServer).GetTags(ctx, req.(*GetTagReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Content_PublishInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServer).PublishInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/teddy.srv.content.Content/PublishInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServer).PublishInfo(ctx, req.(*PublishInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Content_EditInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServer).EditInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/teddy.srv.content.Content/EditInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServer).EditInfo(ctx, req.(*EditInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Content_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/teddy.srv.content.Content/GetInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServer).GetInfo(ctx, req.(*GetInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Content_GetInfos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInfosReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServer).GetInfos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/teddy.srv.content.Content/GetInfos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServer).GetInfos(ctx, req.(*GetInfosReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Content_DeleteInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoIDAndUIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServer).DeleteInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/teddy.srv.content.Content/DeleteInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServer).DeleteInfo(ctx, req.(*InfoIDAndUIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Content_WatchInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoIDAndUIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServer).WatchInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/teddy.srv.content.Content/WatchInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServer).WatchInfo(ctx, req.(*InfoIDAndUIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Content_GetSegments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSegmentsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServer).GetSegments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/teddy.srv.content.Content/GetSegments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServer).GetSegments(ctx, req.(*GetSegmentsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Content_GetSegment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoIDAndUIDAndSegIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServer).GetSegment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/teddy.srv.content.Content/GetSegment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServer).GetSegment(ctx, req.(*InfoIDAndUIDAndSegIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Content_PublishSegment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishSegmentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServer).PublishSegment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/teddy.srv.content.Content/PublishSegment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServer).PublishSegment(ctx, req.(*PublishSegmentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Content_EditSegment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditSegmentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServer).EditSegment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/teddy.srv.content.Content/EditSegment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServer).EditSegment(ctx, req.(*EditSegmentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Content_DeleteSegment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoIDAndUIDAndSegIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServer).DeleteSegment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/teddy.srv.content.Content/DeleteSegment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServer).DeleteSegment(ctx, req.(*InfoIDAndUIDAndSegIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Content_ThumbUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoIDAndUIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServer).ThumbUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/teddy.srv.content.Content/ThumbUp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServer).ThumbUp(ctx, req.(*InfoIDAndUIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Content_DeleteThumbUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoIDAndUIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServer).DeleteThumbUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/teddy.srv.content.Content/DeleteThumbUp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServer).DeleteThumbUp(ctx, req.(*InfoIDAndUIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Content_GetUserThumbUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UIDPageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServer).GetUserThumbUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/teddy.srv.content.Content/GetUserThumbUp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServer).GetUserThumbUp(ctx, req.(*UIDPageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Content_GetInfoThumbUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoIDPageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServer).GetInfoThumbUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/teddy.srv.content.Content/GetInfoThumbUp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServer).GetInfoThumbUp(ctx, req.(*InfoIDPageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Content_ThumbDown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoIDAndUIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServer).ThumbDown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/teddy.srv.content.Content/ThumbDown",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServer).ThumbDown(ctx, req.(*InfoIDAndUIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Content_DeleteThumbDown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoIDAndUIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServer).DeleteThumbDown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/teddy.srv.content.Content/DeleteThumbDown",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServer).DeleteThumbDown(ctx, req.(*InfoIDAndUIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Content_GetUserThumbDown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UIDPageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServer).GetUserThumbDown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/teddy.srv.content.Content/GetUserThumbDown",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServer).GetUserThumbDown(ctx, req.(*UIDPageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Content_GetInfoThumbDown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoIDPageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServer).GetInfoThumbDown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/teddy.srv.content.Content/GetInfoThumbDown",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServer).GetInfoThumbDown(ctx, req.(*InfoIDPageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Content_Favorite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoIDAndUIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServer).Favorite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/teddy.srv.content.Content/Favorite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServer).Favorite(ctx, req.(*InfoIDAndUIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Content_DeleteFavorite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoIDAndUIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServer).DeleteFavorite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/teddy.srv.content.Content/DeleteFavorite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServer).DeleteFavorite(ctx, req.(*InfoIDAndUIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Content_GetUserFavorite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UIDPageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServer).GetUserFavorite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/teddy.srv.content.Content/GetUserFavorite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServer).GetUserFavorite(ctx, req.(*UIDPageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Content_GetInfoFavorite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoIDPageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServer).GetInfoFavorite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/teddy.srv.content.Content/GetInfoFavorite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServer).GetInfoFavorite(ctx, req.(*InfoIDPageReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Content_serviceDesc = grpc.ServiceDesc{
	ServiceName: "teddy.srv.content.Content",
	HandlerType: (*ContentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTags",
			Handler:    _Content_GetTags_Handler,
		},
		{
			MethodName: "PublishInfo",
			Handler:    _Content_PublishInfo_Handler,
		},
		{
			MethodName: "EditInfo",
			Handler:    _Content_EditInfo_Handler,
		},
		{
			MethodName: "GetInfo",
			Handler:    _Content_GetInfo_Handler,
		},
		{
			MethodName: "GetInfos",
			Handler:    _Content_GetInfos_Handler,
		},
		{
			MethodName: "DeleteInfo",
			Handler:    _Content_DeleteInfo_Handler,
		},
		{
			MethodName: "WatchInfo",
			Handler:    _Content_WatchInfo_Handler,
		},
		{
			MethodName: "GetSegments",
			Handler:    _Content_GetSegments_Handler,
		},
		{
			MethodName: "GetSegment",
			Handler:    _Content_GetSegment_Handler,
		},
		{
			MethodName: "PublishSegment",
			Handler:    _Content_PublishSegment_Handler,
		},
		{
			MethodName: "EditSegment",
			Handler:    _Content_EditSegment_Handler,
		},
		{
			MethodName: "DeleteSegment",
			Handler:    _Content_DeleteSegment_Handler,
		},
		{
			MethodName: "ThumbUp",
			Handler:    _Content_ThumbUp_Handler,
		},
		{
			MethodName: "DeleteThumbUp",
			Handler:    _Content_DeleteThumbUp_Handler,
		},
		{
			MethodName: "GetUserThumbUp",
			Handler:    _Content_GetUserThumbUp_Handler,
		},
		{
			MethodName: "GetInfoThumbUp",
			Handler:    _Content_GetInfoThumbUp_Handler,
		},
		{
			MethodName: "ThumbDown",
			Handler:    _Content_ThumbDown_Handler,
		},
		{
			MethodName: "DeleteThumbDown",
			Handler:    _Content_DeleteThumbDown_Handler,
		},
		{
			MethodName: "GetUserThumbDown",
			Handler:    _Content_GetUserThumbDown_Handler,
		},
		{
			MethodName: "GetInfoThumbDown",
			Handler:    _Content_GetInfoThumbDown_Handler,
		},
		{
			MethodName: "Favorite",
			Handler:    _Content_Favorite_Handler,
		},
		{
			MethodName: "DeleteFavorite",
			Handler:    _Content_DeleteFavorite_Handler,
		},
		{
			MethodName: "GetUserFavorite",
			Handler:    _Content_GetUserFavorite_Handler,
		},
		{
			MethodName: "GetInfoFavorite",
			Handler:    _Content_GetInfoFavorite_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/zhsyourai/teddy-backend/common/proto/content/content.proto",
}

func init() {
	proto.RegisterFile("github.com/zhsyourai/teddy-backend/common/proto/content/content.proto", fileDescriptor_content_14c3d90b04e7be7b)
}

var fileDescriptor_content_14c3d90b04e7be7b = []byte{
	// 1606 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x58, 0x4b, 0x73, 0x1b, 0xc5,
	0x13, 0xb7, 0xde, 0x52, 0xcb, 0x96, 0x93, 0x49, 0xfe, 0xf6, 0xfe, 0x95, 0xc4, 0xc8, 0x5b, 0xa9,
	0x42, 0x15, 0x88, 0x5c, 0x71, 0x20, 0x05, 0x09, 0x1c, 0x6c, 0xcb, 0x38, 0x0a, 0x09, 0x09, 0x6b,
	0x29, 0x81, 0x54, 0x71, 0x58, 0x49, 0xe3, 0xd5, 0x56, 0xb4, 0xbb, 0x62, 0x67, 0xe4, 0x94, 0x72,
	0xe0, 0xc4, 0x01, 0xee, 0x7c, 0x09, 0x3e, 0x03, 0x07, 0x8a, 0x2f, 0xc4, 0x95, 0x1b, 0x45, 0xcd,
	0x6b, 0xb5, 0xb2, 0x77, 0xf5, 0x88, 0x15, 0x8a, 0x8b, 0x3d, 0x8f, 0xee, 0xdf, 0x74, 0xff, 0x7a,
	0xba, 0x7b, 0xb4, 0x70, 0x68, 0xd9, 0xb4, 0x37, 0x6c, 0xd7, 0x3a, 0x9e, 0xb3, 0xf3, 0xa6, 0x47,
	0x46, 0xde, 0xd0, 0x37, 0xed, 0x1d, 0x8a, 0xbb, 0xdd, 0xd1, 0xed, 0xb6, 0xd9, 0x79, 0x85, 0xdd,
	0xee, 0x4e, 0xc7, 0x73, 0x1c, 0xcf, 0xdd, 0x19, 0xf8, 0x1e, 0xf5, 0x76, 0x3a, 0x9e, 0x4b, 0xb1,
	0x4b, 0xd5, 0xff, 0x1a, 0x5f, 0x45, 0x97, 0xb9, 0x46, 0x8d, 0xf8, 0xa7, 0x35, 0xb9, 0x51, 0xbe,
	0x1b, 0x42, 0xb6, 0xbc, 0xbe, 0xe9, 0x5a, 0x02, 0xa1, 0x3d, 0x3c, 0xd9, 0x19, 0xd0, 0xd1, 0x00,
	0x93, 0x1d, 0xec, 0x0c, 0xe8, 0x48, 0xfc, 0x15, 0x38, 0xe5, 0x07, 0xb3, 0x95, 0xa8, 0xed, 0x60,
	0x42, 0x4d, 0x67, 0x30, 0x1e, 0x09, 0x65, 0xfd, 0x43, 0x48, 0x1f, 0x7b, 0x3e, 0x45, 0x08, 0xd2,
	0xae, 0xe9, 0x60, 0x2d, 0x51, 0x49, 0x54, 0x0b, 0x06, 0x1f, 0xa3, 0x4b, 0x90, 0x32, 0x49, 0x47,
	0x4b, 0x56, 0x12, 0xd5, 0xbc, 0xc1, 0x86, 0xfa, 0x6f, 0x09, 0x48, 0x35, 0x4d, 0x8b, 0xed, 0x50,
	0xd3, 0x92, 0xc2, 0x6c, 0xc8, 0xf4, 0xd9, 0x51, 0x5c, 0xb8, 0x60, 0xf0, 0x31, 0xba, 0x0a, 0x99,
	0x21, 0x31, 0x2d, 0xac, 0xa5, 0x2a, 0x89, 0x6a, 0xda, 0x10, 0x13, 0x74, 0x1f, 0xa0, 0xe3, 0x63,
	0x93, 0xe2, 0xa6, 0xed, 0x60, 0x2d, 0x5d, 0x49, 0x54, 0x8b, 0xbb, 0xe5, 0x9a, 0xe5, 0x79, 0x56,
	0x1f, 0xd7, 0x94, 0xe1, 0xb5, 0xa6, 0xb2, 0xd3, 0x08, 0x49, 0xa3, 0xcf, 0xa0, 0xd8, 0x37, 0x09,
	0x6d, 0x11, 0xa1, 0x9c, 0x99, 0xa9, 0x1c, 0x16, 0xd7, 0x77, 0x01, 0x9a, 0xa6, 0xb5, 0xe7, 0x76,
	0x9b, 0xcc, 0xba, 0xb9, 0x7c, 0xd0, 0xff, 0xc8, 0x43, 0xba, 0xe1, 0x9e, 0x78, 0x68, 0x03, 0xb2,
	0xb6, 0x7b, 0xe2, 0x35, 0xea, 0x52, 0x43, 0xce, 0x18, 0xcc, 0xd0, 0xee, 0x4a, 0x1d, 0x36, 0x64,
	0x92, 0xe6, 0x90, 0xf6, 0x3c, 0x9f, 0xfb, 0x5d, 0x30, 0xe4, 0x8c, 0xd1, 0x41, 0x6d, 0xda, 0x17,
	0x3e, 0x17, 0x0c, 0x31, 0x41, 0x1a, 0xe4, 0xc8, 0xd0, 0x71, 0x4c, 0x7f, 0xc4, 0xdd, 0x29, 0x18,
	0x6a, 0xca, 0x76, 0x3a, 0xde, 0xd0, 0xa5, 0xfe, 0x48, 0xcb, 0x8a, 0x1d, 0x39, 0x65, 0x34, 0xc8,
	0x1b, 0xc3, 0x69, 0xc8, 0xcd, 0xa6, 0x21, 0x24, 0x8e, 0x8e, 0xa1, 0xd4, 0xf1, 0x4e, 0xb1, 0x6f,
	0x60, 0xe2, 0x0d, 0xfd, 0x0e, 0x26, 0x5a, 0xbe, 0x92, 0xaa, 0x16, 0x77, 0x3f, 0xa8, 0x9d, 0xbb,
	0x90, 0x35, 0xe6, 0x7a, 0xed, 0x60, 0x42, 0xfa, 0x90, 0x99, 0x60, 0x9c, 0x81, 0x60, 0x26, 0x0d,
	0x86, 0xed, 0xbe, 0x4d, 0x7a, 0xdc, 0xa4, 0xc2, 0x6c, 0x93, 0x42, 0xe2, 0x68, 0x1f, 0x4a, 0x2c,
	0x50, 0x06, 0x3e, 0xb5, 0xf1, 0x6b, 0x0e, 0x00, 0x33, 0x01, 0xce, 0x68, 0xa0, 0x2d, 0x80, 0xd7,
	0x26, 0xed, 0xf4, 0x0e, 0x18, 0x49, 0x5a, 0xb1, 0x92, 0xa8, 0xa6, 0x8c, 0xd0, 0x0a, 0xba, 0x03,
	0x69, 0x6a, 0x5a, 0x44, 0x5b, 0xe5, 0xce, 0xde, 0x88, 0x70, 0x76, 0x7c, 0x39, 0x0c, 0x2e, 0xca,
	0x22, 0x40, 0x7b, 0x43, 0xa7, 0xdd, 0x1a, 0x68, 0x6b, 0x1c, 0x4f, 0x4d, 0xd1, 0x75, 0x28, 0xd8,
	0xa4, 0x29, 0xf7, 0x4a, 0x3c, 0x41, 0xc6, 0x0b, 0xa8, 0x02, 0x45, 0x29, 0xf8, 0xd8, 0x26, 0x54,
	0x5b, 0xaf, 0xa4, 0xaa, 0x05, 0x23, 0xbc, 0xc4, 0xf4, 0xf9, 0xb4, 0xee, 0xbd, 0x76, 0xb5, 0x4b,
	0x1c, 0x7b, 0xbc, 0xc0, 0xf4, 0x25, 0x18, 0xdf, 0xbf, 0xcc, 0xf1, 0xc3, 0x4b, 0xe8, 0x26, 0xac,
	0x05, 0xe2, 0xfc, 0x0c, 0xc4, 0xcf, 0x98, 0x5c, 0x64, 0xa7, 0x9c, 0x98, 0xa7, 0x9e, 0x6f, 0x53,
	0x4c, 0xb4, 0x2b, 0xe2, 0x94, 0x60, 0x81, 0x11, 0x66, 0x93, 0x2f, 0xe4, 0x54, 0xbb, 0xca, 0x0f,
	0x09, 0xad, 0x20, 0x1d, 0x56, 0x95, 0x30, 0x3f, 0xe2, 0x7f, 0xfc, 0x88, 0x89, 0x35, 0x15, 0xb8,
	0x27, 0x5e, 0xd7, 0x3e, 0x19, 0xf1, 0xc0, 0x6d, 0xcc, 0x17, 0xb8, 0xb1, 0x06, 0xb3, 0xb2, 0x63,
	0xba, 0x22, 0x92, 0xda, 0xa6, 0xe0, 0x32, 0x58, 0x60, 0x59, 0x73, 0x6a, 0xf6, 0xed, 0xae, 0xa6,
	0xf1, 0x1d, 0x31, 0x41, 0x65, 0xc8, 0x9b, 0x7e, 0xa7, 0x67, 0x9f, 0xe2, 0xae, 0xf6, 0x7f, 0xbe,
	0x11, 0xcc, 0x51, 0x15, 0xd6, 0x1f, 0x9b, 0x14, 0x13, 0x7a, 0x8c, 0x2d, 0x07, 0xbb, 0xb4, 0x51,
	0xd7, 0xca, 0x3c, 0x7f, 0xce, 0x2e, 0x33, 0x0f, 0xe5, 0x44, 0x5c, 0x9a, 0x6b, 0x9c, 0xa2, 0x89,
	0xb5, 0xf2, 0x1e, 0x5c, 0x89, 0xb8, 0xff, 0x2c, 0xed, 0x5f, 0xe1, 0x91, 0xaa, 0x1e, 0xaf, 0xf0,
	0x48, 0x1a, 0x3a, 0x54, 0xe5, 0x43, 0x4c, 0xee, 0x27, 0x3f, 0x49, 0xe8, 0x7f, 0x26, 0x20, 0x27,
	0x31, 0x51, 0x09, 0x92, 0x76, 0x57, 0xaa, 0x25, 0x45, 0xb1, 0x90, 0x65, 0x25, 0x39, 0x51, 0x56,
	0x4a, 0x90, 0x74, 0x3d, 0x5e, 0x40, 0x52, 0x46, 0xd2, 0xf5, 0x62, 0x8a, 0xc7, 0x06, 0x64, 0xfb,
	0x66, 0x1b, 0xf7, 0x89, 0x96, 0xe1, 0xc1, 0x91, 0x33, 0xb4, 0xc7, 0x4a, 0x07, 0xbf, 0xd4, 0x5a,
	0x96, 0x5f, 0xf7, 0xf7, 0x23, 0xae, 0xbb, 0x34, 0xa9, 0x76, 0x20, 0xe6, 0x22, 0xaf, 0x95, 0x5e,
	0xf9, 0x3e, 0xac, 0x86, 0x37, 0x16, 0x72, 0xf8, 0xa7, 0x04, 0x14, 0x8e, 0x30, 0x6d, 0x9a, 0x96,
	0x81, 0xbf, 0x67, 0x65, 0x75, 0xc0, 0xba, 0x00, 0x53, 0x5d, 0x33, 0xf8, 0x98, 0xad, 0x11, 0xfb,
	0x8d, 0x50, 0x5d, 0x33, 0xf8, 0x38, 0x28, 0xbf, 0xa9, 0x50, 0x0b, 0xb9, 0x0d, 0x19, 0xe2, 0xf9,
	0x94, 0x68, 0x69, 0xee, 0xc6, 0x66, 0x94, 0x1b, 0x9e, 0x4f, 0x0d, 0x21, 0xa5, 0x8a, 0x71, 0x26,
	0x28, 0xc6, 0xfa, 0x10, 0xa0, 0xd5, 0xa8, 0x3f, 0x33, 0x2d, 0xbc, 0x88, 0x29, 0xc1, 0xb1, 0xa9,
	0x45, 0x8e, 0x4d, 0x8f, 0x8f, 0xfd, 0x14, 0x8a, 0x82, 0x00, 0x62, 0x60, 0x32, 0x40, 0xb7, 0x64,
	0xed, 0x49, 0x70, 0xb8, 0x8d, 0xe8, 0xda, 0x23, 0x8a, 0x8e, 0xfe, 0x57, 0x12, 0x4a, 0xcf, 0x44,
	0x6d, 0x64, 0xd5, 0x97, 0x99, 0x2d, 0xf1, 0x13, 0x51, 0x3d, 0x26, 0x19, 0xdd, 0x63, 0x52, 0x31,
	0x3d, 0x26, 0x1d, 0xdb, 0x63, 0x32, 0x93, 0x3d, 0x46, 0x95, 0xcb, 0xec, 0xfc, 0xe5, 0xf2, 0xbb,
	0x73, 0x8d, 0x25, 0xc7, 0x95, 0x3f, 0x8e, 0x50, 0x9e, 0xf4, 0x70, 0xae, 0x16, 0x33, 0x51, 0x27,
	0xf2, 0x67, 0xea, 0xc4, 0x32, 0xf2, 0xf4, 0xe7, 0x14, 0x14, 0x0f, 0xbb, 0x36, 0x55, 0xb4, 0xff,
	0x97, 0x5a, 0xbe, 0x0a, 0x47, 0x6e, 0xfe, 0x70, 0xbc, 0x8c, 0xe9, 0xf3, 0xbb, 0x11, 0xca, 0x21,
	0xb7, 0x17, 0x8f, 0x45, 0xe1, 0x1d, 0xc4, 0xe2, 0xd7, 0x04, 0x94, 0x8e, 0xb0, 0xaa, 0xd5, 0x64,
	0x91, 0xe4, 0x1d, 0x87, 0x2d, 0x15, 0x15, 0xb6, 0xf4, 0x44, 0xd8, 0x22, 0xcb, 0x67, 0x90, 0xfe,
	0xd9, 0x79, 0xd2, 0x5f, 0xdf, 0x87, 0xbc, 0xb2, 0x13, 0xdd, 0x83, 0x3c, 0x91, 0x63, 0x99, 0xed,
	0xe5, 0xf8, 0xd2, 0x6b, 0x04, 0xb2, 0xfa, 0x8f, 0x49, 0xb8, 0x2c, 0x73, 0x42, 0x6d, 0x2e, 0x74,
	0x03, 0x2f, 0xd6, 0x2f, 0xbe, 0x3c, 0xdb, 0x2f, 0xee, 0xc4, 0xa7, 0xec, 0xd8, 0xbc, 0x77, 0xd0,
	0x39, 0x7e, 0x49, 0x42, 0x89, 0xdd, 0xc5, 0xb7, 0xe2, 0xe0, 0x2a, 0x64, 0x08, 0xb6, 0x82, 0xb8,
	0x8b, 0x89, 0x64, 0x26, 0x7d, 0x9e, 0x99, 0x4c, 0x34, 0x33, 0xd9, 0x09, 0x66, 0x1e, 0x8e, 0x99,
	0x11, 0xa9, 0x57, 0x8b, 0xc9, 0x9e, 0x77, 0x4a, 0xcb, 0xb7, 0xb0, 0xd9, 0xe0, 0x5e, 0xef, 0xb9,
	0xdd, 0x16, 0xff, 0x7b, 0xcc, 0x7c, 0x5b, 0x02, 0x3d, 0xfa, 0x3d, 0x80, 0x23, 0xbc, 0x78, 0xc9,
	0xd3, 0x7f, 0x4f, 0xf0, 0x16, 0xc7, 0x14, 0xc9, 0xbf, 0xd9, 0x5a, 0x63, 0xe2, 0xb7, 0x78, 0xbb,
	0xd2, 0x3f, 0x87, 0xd5, 0xb1, 0x03, 0x64, 0xc0, 0x2c, 0x63, 0xde, 0xaa, 0xbc, 0xdd, 0x8c, 0xf9,
	0x39, 0x64, 0x08, 0x29, 0xfd, 0x01, 0xac, 0x87, 0x63, 0x12, 0xdb, 0xa7, 0xa3, 0x9e, 0x77, 0xfa,
	0x0f, 0xb0, 0x26, 0x94, 0xd5, 0xcb, 0x24, 0x8e, 0x78, 0x45, 0x6b, 0x32, 0x82, 0xd6, 0x54, 0x14,
	0xad, 0x73, 0x3d, 0x94, 0xf4, 0xa7, 0x50, 0x6c, 0x35, 0xea, 0x2f, 0x6c, 0x2a, 0x7e, 0x7f, 0x9d,
	0x37, 0xbc, 0x06, 0x69, 0xca, 0x9e, 0xf3, 0xc9, 0x99, 0xcf, 0x79, 0x2e, 0xa7, 0x1f, 0x40, 0xb1,
	0x45, 0xb0, 0xdf, 0xa8, 0x0b, 0x2e, 0x3f, 0x82, 0x8c, 0x4d, 0xb1, 0xa3, 0xb8, 0xdc, 0x8a, 0x30,
	0x27, 0x74, 0xbe, 0x21, 0x84, 0xf5, 0x6f, 0xa0, 0x24, 0x58, 0x09, 0x0c, 0x53, 0xb4, 0x74, 0x27,
	0x68, 0x59, 0xdc, 0xbc, 0x7d, 0x28, 0x0a, 0x64, 0x61, 0xde, 0x5d, 0x48, 0xd9, 0x5d, 0x65, 0xdc,
	0x76, 0x4c, 0xa0, 0x43, 0xf6, 0x31, 0xe9, 0xdd, 0xbf, 0x4b, 0x90, 0x93, 0x19, 0x8c, 0x1a, 0x90,
	0x93, 0xef, 0x3b, 0x74, 0x3d, 0x42, 0x3d, 0x78, 0xfc, 0x96, 0xb7, 0x62, 0x77, 0xb9, 0x25, 0xfa,
	0x0a, 0x7a, 0x04, 0xc5, 0xd0, 0x63, 0x08, 0x6d, 0xcf, 0x7c, 0x2c, 0x95, 0x37, 0xce, 0xb9, 0x7b,
	0xe8, 0x0c, 0xe8, 0x48, 0x5f, 0x41, 0x75, 0xc8, 0xab, 0x4e, 0x8e, 0xb6, 0xa6, 0xb7, 0xf9, 0x29,
	0x28, 0x07, 0xdc, 0x39, 0x0e, 0x72, 0x23, 0xda, 0x7c, 0x85, 0x11, 0x97, 0x23, 0xfa, 0x0a, 0x7a,
	0x02, 0x79, 0x95, 0x5d, 0x68, 0x2b, 0x1e, 0x85, 0xd5, 0x8e, 0xf2, 0x7b, 0x53, 0xf7, 0x25, 0x4b,
	0x50, 0xc7, 0x7d, 0x4c, 0x31, 0x37, 0x4b, 0x8f, 0x0d, 0x59, 0x90, 0x8c, 0x53, 0xfc, 0x6b, 0x40,
	0xe1, 0x85, 0x49, 0x3b, 0xbd, 0x25, 0x40, 0x3d, 0xe5, 0x45, 0x30, 0xe8, 0xfe, 0xdb, 0xd1, 0x8e,
	0x84, 0x5e, 0x31, 0xe5, 0x6b, 0xf1, 0xcf, 0x01, 0xa2, 0xaf, 0xa0, 0xe7, 0xbc, 0x1c, 0xab, 0x5f,
	0x8b, 0xb7, 0x66, 0x18, 0x17, 0x6a, 0x04, 0xe5, 0x29, 0xef, 0x0c, 0x7d, 0x05, 0x3d, 0x0b, 0x7e,
	0x54, 0x28, 0xec, 0x9b, 0xf3, 0xb4, 0xf8, 0x29, 0xae, 0x3f, 0x12, 0x8f, 0x65, 0x05, 0xb7, 0x3d,
	0xb3, 0x2f, 0x4e, 0xc1, 0x6a, 0xc1, 0x9a, 0x88, 0xee, 0xdb, 0x38, 0x1e, 0x0f, 0x7b, 0x04, 0x39,
	0xf5, 0x49, 0xe6, 0x62, 0x61, 0x7e, 0xa2, 0xec, 0x5b, 0x0e, 0xdc, 0xd7, 0xfc, 0x6d, 0xcb, 0xea,
	0xa5, 0xc2, 0xbb, 0x11, 0x5d, 0x20, 0x65, 0x77, 0x88, 0xac, 0x22, 0xa1, 0x7a, 0xa6, 0xaf, 0xa0,
	0x26, 0x87, 0x64, 0x6b, 0xc1, 0x47, 0xa8, 0x58, 0x9d, 0x69, 0xa8, 0xa1, 0x22, 0x2e, 0x32, 0x65,
	0xfc, 0xcd, 0xe9, 0xa2, 0x99, 0xb2, 0x1e, 0xa2, 0x70, 0x09, 0x80, 0xc7, 0x70, 0x29, 0x4c, 0x22,
	0x47, 0xbc, 0x30, 0x8d, 0xcf, 0x39, 0x68, 0x40, 0xa3, 0xf8, 0x1a, 0xb7, 0x04, 0x22, 0x1f, 0x42,
	0x7e, 0xfc, 0x5d, 0xed, 0x42, 0x6e, 0x7f, 0x05, 0x25, 0xc1, 0xe3, 0x92, 0xf0, 0x0c, 0x58, 0x97,
	0x34, 0x06, 0x80, 0x17, 0x66, 0xb1, 0xc5, 0x31, 0xd9, 0x5a, 0x80, 0xb9, 0x04, 0x12, 0xf7, 0x0b,
	0x2f, 0xd5, 0x63, 0xba, 0x9d, 0xe5, 0x7e, 0xdc, 0xfd, 0x27, 0x00, 0x00, 0xff, 0xff, 0xe5, 0xac,
	0x99, 0x24, 0x8b, 0x19, 0x00, 0x00,
}
