databases:
  mongodb: mongodb://mongodb-primary:27017,mongodb-secondary:27017/admin?replicaSet=replicaset

object_store:
  minio:
    endpoint: minio:9000
    access_key: FSBDQFL0XWDCP243O49Q
    secret_key: T9xikDYZaobOqfDwV38SAqzxDTjZvcZHDo6I36VN