server:
  address: 0.0.0.0
  port: 9090

databases:
  mongodb:
    - address: 127.0.0.1:27017
      username: teddy
      password: teddy
      auth_db: teddy

jwt_pkcs8: ""

mail:
  host: test
  port: 555
  username: teddy
  password: teddy