version: '3.3'

services:
  mongodb-primary:
    image: 'bitnami/mongodb:latest'
    networks:
      - overlay
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
    volumes:
      - 'mongodb_master_data:/bitnami'

  mongodb-secondary:
    image: 'bitnami/mongodb:latest'
    networks:
      - overlay
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_PORT_NUMBER=27017

  mongodb-arbiter:
    image: 'bitnami/mongodb:latest'
    networks:
      - overlay
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_PORT_NUMBER=27017

  minio:
    image: minio/minio
    networks:
      - overlay
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: FSBDQFL0XWDCP243O49Q
      MINIO_SECRET_KEY: T9xikDYZaobOqfDwV38SAqzxDTjZvcZHDo6I36VN
    command: server /data

  srv-message:
    image: srv-message:latest
    restart: always
    networks:
      - overlay
    configs:
      - source: srv_message_config
        target: /app/config
    secrets:
      - source: srv_message_secret
        target: /app/secret

  srv-content:
    image: srv-content:latest
    restart: always
    networks:
      - overlay
    configs:
      - source: srv_content_config
        target: /app/config
    secrets:
      - source: srv_content_secret
        target: /app/secret

  srv-captcha:
    image: srv-captcha:latest
    restart: always
    networks:
      - overlay
    configs:
      - source: srv_captcha_config
        target: /app/config
    secrets:
      - source: srv_captcha_secret
        target: /app/secret

  srv-uaa:
    image: srv-uaa:latest
    restart: always
    networks:
      - overlay
    configs:
      - source: srv_uaa_config
        target: /app/config
    secrets:
      - source: srv_uaa_secret
        target: /app/secret

  api-base:
    image: api-base:latest
    ports:
      - "8080:8080"
    restart: always
    networks:
      - overlay
    configs:
      - source: api_base_config
        target: /app/config
    secrets:
      - source: api_base_secret
        target: /app/secret

  api-content:
    image: api-content:latest
    ports:
      - "8081:8081"
    restart: always
    networks:
      - overlay
    configs:
      - source: api_content_config
        target: /app/secret
    secrets:
      - source: api_content_secret
        target: /app/secret

  api-uaa:
    image: api-uaa:latest
    ports:
      - "8083:8083"
    restart: always
    networks:
      - overlay
    configs:
      - source: api_uaa_config
        target: /app/config
    secrets:
      - source: api_uaa_secret
        target: /app/secret

configs:
  srv_message_config:
    config.yaml: |-
      server:
        address: 0.0.0.0
        port: 9092
  srv_content_config:
    config.yaml: |-
      server:
        address: 0.0.0.0
        port: 9091
  srv_captcha_config:
    config.yaml: |-
      server:
        address: 0.0.0.0
        port: 9090
  srv_uaa_config:
    config.yaml: |-
      server:
        address: 0.0.0.0
        port: 9093
  api_content_config:
    config.yaml: |-
      server:
        address: 0.0.0.0
        port: 8081
  api_base_config:
    config.yaml: |-
      server:
        address: 0.0.0.0
        port: 8080
  api_uaa_config:
    config.yaml: |-
      server:
        address: 0.0.0.0
        port: 8083

secrets:
  srv_message_secret:
    config.yaml: |-
      databases:
        mongodb: mongodb://mongodb-primary:27017,mongodb-secondary:27017/admin?replicaSet=replicaset

      mail:
        host: smtp.163.com
        port: 465
        username: zhsyourai@163.com
        password: 8228zhs..
  srv_content_secret:
    config.yaml: |-
      databases:
        mongodb: mongodb://mongodb-primary:27017,mongodb-secondary:27017/admin?replicaSet=replicaset

      object_store:
        minio:
          endpoint: minio:9000
          access_key: FSBDQFL0XWDCP243O49Q
          secret_key: T9xikDYZaobOqfDwV38SAqzxDTjZvcZHDo6I36VN
  srv_captcha_secret:
    config.yaml: |-
      databases:
        mongodb: mongodb://mongodb-primary:27017,mongodb-secondary:27017/admin?replicaSet=replicaset
  srv_uaa_secret:
    config.yaml: |-
      databases:
        mongodb: mongodb://mongodb-primary:27017,mongodb-secondary:27017/admin?replicaSet=replicaset
  api_uaa_secret:
    config.yaml: |-
      JWTPkcs8: |-
          -----BEGIN PRIVATE KEY-----
          MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDk6+ozDV9z2CZb
          YE5sHCkint7a+SpOQzfhYnNcRXeFA7TyI+0oH22pNi0Obo+uWbCI+pbo48W+teZl
          64doD+L7Q/qz/KYuWnaDpVW5K+FRLmxIKDL+nmd62fQr1wqdzBeHG/u4YPmv/P4q
          LGLnq2Wt+STUFVBNUL45noiYHzhtn4o/NoW2XQzYgrnqbrK+EDJKUWlQ4qdpID6d
          bpvHw5kYFhd9lgT45ZtyIHOrGwwRHm3SP+2eAn0zAavWq/AWFuycY0uGE9eNBbh4
          BiKuNf5OfEFf48PM5unG3l4YhHMeNHBiE6DuigCDP9JV01dw369SzylG6BuV9+uU
          e6ssxkQ/AgMBAAECggEAT98IHbviu/aEm4kkk4/Xwl6P/vLEkf3d92N0QJN0OhKr
          BXkHe+JLTqi6W7izpO9iKsjT8nnWOs4YjyL4YZR5a5WyWS4jhTTG+POszyjCOqLp
          4Ns1v6ThEfoNuWYULC5TXy6iSxh6xa6Nt4U5FP+2QFcXRHATToaHeG8Z1Ym/FG/W
          vlxyeeWBttQPqEYxydJ+reHUvpYl0w/hVgmBG9R2WHuKCs+Y0zbfoDdbJtWPwwKu
          hZxsUxqbgbfr6NMl+e9eZCauxZ2FPSgYCYkm7sCz8u7Wk1IP76ZEQ9vS+9ks/ACy
          GbukEVuY40YTy/LP7YzbG5sOVf1NxMl/QWLXTQwLsQKBgQD4Y1O/rltwxk/NCCsb
          wdoYgC+J30Cw4LQizBBrNhpx9R8K95LyRT+NUvRycgAvDbPyNjP4P15GBNlc1LWs
          AAWfbjlRgXFdPxHgyxHhVwvgwCsBNrTkIeIelADpUvqcpxeU9A8YT92277HrFBVl
          GZ8mis67OL/VhULdajSd9ow4iwKBgQDr794yRF+c35jYXqCJFHr4iMQuNj2q7R6Q
          JEYJ/wZX9iOOlzwnEZskJIMuaBipjTrFrUFLmp4NFLoxOAZyJ8lVBc2DNNcFR6VH
          xU10/5LgaMfc67Y3FkVZUKT/iMn6xVRGRr8IggQPA2kaOBtdWEuzQJ81GjrzZT4i
          cRmoHcKlnQKBgEzxD8dHrmGfvKaJijj98p42TwOJWZOw93vz9H4Rc12rjaMrD6Tm
          mIohkUFGWRI6T2yPJ8gVcRGFfQOJjIEsPJGnZi/+ReyZleMpZG+GNFK5lFi65ovo
          hw/rzuB36NPP2rk0ZNymGMsLMvTb8siviCI7S1CpgpsUvaKyvHvWHJeDAoGANrw7
          LCY4mEg3SVsKm0KpFKeF+8KRo+nGwWHo7cDAU//CV/418kpfV48w778umYcuL1X2
          Y/fG2voICAsbU7hvOM5T0zCbAZqReYkIYzA3fuBQHayBZV5BUGspHC87zHWjC3q2
          Lt8a2fDMnUyO7KTjSv6e8M7ZBkZil9LtRNdCpPECgYAkkP/u7yqI1/fyfij1EJW4
          XFcZMYfFP7LHVIKU8b4hfzJmDBjD4t/7zC2dzYYxmUTQXB4o8gOWhauBOV2qVa7L
          zL5vu2PbU2Pbwc2yZsVio245oYU6xAVnZJ7Xlr/2WNa7dULiLYyZCMH944ljYASJ
          r0mQwY8VRGvzT8HRC33OMw==
          -----END PRIVATE KEY-----
  api_content_secret:
    config.yaml: |-
      object_store:
        minio:
          bucket: teddy
          endpoint: minio:9000
          access_key: FSBDQFL0XWDCP243O49Q
          secret_key: T9xikDYZaobOqfDwV38SAqzxDTjZvcZHDo6I36VN

volumes:
  mongodb_master_data:
    driver: local
  minio_data:
    driver: local

networks:
  overlay: