version: '3.3'

services:
  mongodb-primary:
    image: 'bitnami/mongodb:latest'
    networks:
      - overlay
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
    volumes:
      - 'mongodb_master_data:/bitnami'

  mongodb-secondary:
    image: 'bitnami/mongodb:latest'
    networks:
      - overlay
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_PORT_NUMBER=27017

  mongodb-arbiter:
    image: 'bitnami/mongodb:latest'
    networks:
      - overlay
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_PORT_NUMBER=27017

  mongo-cli:
    networks:
      - overlay
    image: 'bitnami/mongodb:latest'

  minio:
    image: minio/minio
    networks:
      - overlay
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: FSBDQFL0XWDCP243O49Q
      MINIO_SECRET_KEY: T9xikDYZaobOqfDwV38SAqzxDTjZvcZHDo6I36VN
    command: server /data

  srv-message:
    image: teddy/message:latest
    restart: always
    networks:
      - overlay
    volumes:
      - ./configs/srv_message/:/app/config/
      - ./secrets/srv_message/:/app/secret/

  srv-content:
    image: teddy/content:latest
    restart: always
    networks:
      - overlay
    volumes:
      - ./configs/srv_content/:/app/config/
      - ./secrets/srv_content/:/app/secret/

  srv-captcha:
    image: teddy/captcha:latest
    restart: always
    networks:
      - overlay
    volumes:
      - ./configs/srv_captcha/:/app/config/
      - ./secrets/srv_captcha/:/app/secret/

  srv-uaa:
    image: teddy/uaa:latest
    restart: always
    networks:
      - overlay
    volumes:
      - ./configs/srv_uaa/:/app/config/
      - ./secrets/srv_uaa/:/app/secret/

  api-base:
    image: teddy/api-base:latest
    ports:
      - "8080:8080"
    restart: always
    networks:
      - overlay
    volumes:
      - ./configs/api_base/:/app/config/

  api-content:
    image: teddy/api-content:latest
    ports:
      - "8081:8081"
    restart: always
    networks:
      - overlay
    volumes:
      - ./configs/api_content/:/app/config/
      - ./secrets/api_content/:/app/secret/

  api-uaa:
    image: teddy/api-uaa:latest
    ports:
      - "8083:8083"
    restart: always
    networks:
      - overlay
    volumes:
      - ./configs/api_uaa/:/app/config/
      - ./secrets/api_uaa/:/app/secret/

volumes:
  mongodb_master_data:
    driver: local
  minio_data:
    driver: local

networks:
  overlay: