version: '3.3'

services:
  mongodb-primary:
    image: 'bitnami/mongodb:latest'
    networks:
      - overlay
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
    volumes:
      - 'mongodb_master_data:/bitnami'

  mongodb-secondary:
    image: 'bitnami/mongodb:latest'
    networks:
      - overlay
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_PORT_NUMBER=27017

  mongodb-arbiter:
    image: 'bitnami/mongodb:latest'
    networks:
      - overlay
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_PRIMARY_HOST=mongodb-primary
      - MONGODB_PRIMARY_PORT_NUMBER=27017

  minio:
    image: minio/minio
    networks:
      - overlay
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: FSBDQFL0XWDCP243O49Q
      MINIO_SECRET_KEY: T9xikDYZaobOqfDwV38SAqzxDTjZvcZHDo6I36VN
    command: server /data

  srv-message:
    image: srv-message:latest
    restart: always
    networks:
      - overlay
    configs:
      - source: srv_message_config
        target: /app/config
    secrets:
      - source: srv_message_secret
        target: /app/secret

  srv-content:
    image: srv-content:latest
    restart: always
    networks:
      - overlay
    configs:
      - source: srv_content_config
        target: /app/config
    secrets:
      - source: srv_content_secret
        target: /app/secret

  srv-captcha:
    image: srv-captcha:latest
    restart: always
    networks:
      - overlay
    configs:
      - source: srv_captcha_config
        target: /app/config
    secrets:
      - source: srv_captcha_secret
        target: /app/secret

  srv-uaa:
    image: srv-uaa:latest
    restart: always
    networks:
      - overlay
    configs:
      - source: srv_uaa_config
        target: /app/config
    secrets:
      - source: srv_uaa_secret
        target: /app/secret

  api-base:
    image: api-base:latest
    ports:
      - "8080:8080"
    restart: always
    networks:
      - overlay
    configs:
      - source: api_base_config
        target: /app/config

  api-content:
    image: api-content:latest
    ports:
      - "8081:8081"
    restart: always
    networks:
      - overlay
    configs:
      - source: api_content_config
        target: /app/secret
    secrets:
      - source: api_content_secret
        target: /app/secret

  api-uaa:
    image: api-uaa:latest
    ports:
      - "8083:8083"
    restart: always
    networks:
      - overlay
    configs:
      - source: api_uaa_config
        target: /app/config
    secrets:
      - source: api_uaa_secret
        target: /app/secret

configs:
  srv_message_config:
    file: ./configs/srv_message/config.yaml
  srv_content_config:
    file: ./configs/srv_content/config.yaml
  srv_captcha_config:
    file: ./configs/srv_captcha/config.yaml
  srv_uaa_config:
    file: ./configs/srv_uaa/config.yaml
  api_content_config:
    file: ./configs/api_content/config.yaml
  api_base_config:
    file: ./configs/api_base/config.yaml
  api_uaa_config:
    file: ./configs/api_uaa/config.yaml

secrets:
  srv_message_secret:
    file: ./secrets/srv_message/config.yaml
  srv_content_secret:
    file: ./secrets/srv_content/config.yaml
  srv_captcha_secret:
    file: ./secrets/srv_captcha/config.yaml
  srv_uaa_secret:
    file: ./secrets/srv_uaa/config.yaml
  api_uaa_secret:
    file: ./secrets/api_uaa/config.yaml
  api_content_secret:
    file: ./secrets/api_content/config.yaml

volumes:
  mongodb_master_data:
    driver: local
  minio_data:
    driver: local

networks:
  overlay: