// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/uaa.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/empty"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type OAuthType int32

const (
	OAuthType_GOOGLE   OAuthType = 0
	OAuthType_WECHAT   OAuthType = 1
	OAuthType_QQ       OAuthType = 2
	OAuthType_SINA     OAuthType = 3
	OAuthType_FACEBOOK OAuthType = 4
	OAuthType_TWITTER  OAuthType = 5
)

var OAuthType_name = map[int32]string{
	0: "GOOGLE",
	1: "WECHAT",
	2: "QQ",
	3: "SINA",
	4: "FACEBOOK",
	5: "TWITTER",
}
var OAuthType_value = map[string]int32{
	"GOOGLE":   0,
	"WECHAT":   1,
	"QQ":       2,
	"SINA":     3,
	"FACEBOOK": 4,
	"TWITTER":  5,
}

func (x OAuthType) String() string {
	return proto.EnumName(OAuthType_name, int32(x))
}
func (OAuthType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_uaa_6e45fa96551cfafa, []int{0}
}

type Account struct {
	Uid                  string               `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Username             string               `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email                string               `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password             []byte               `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	AccountExpired       bool                 `protobuf:"varint,5,opt,name=accountExpired,proto3" json:"accountExpired,omitempty"`
	AccountLocked        bool                 `protobuf:"varint,6,opt,name=accountLocked,proto3" json:"accountLocked,omitempty"`
	CredentialsExpired   bool                 `protobuf:"varint,7,opt,name=credentialsExpired,proto3" json:"credentialsExpired,omitempty"`
	Roles                []string             `protobuf:"bytes,8,rep,name=roles,proto3" json:"roles,omitempty"`
	OauthUserIds         map[uint32]string    `protobuf:"bytes,9,rep,name=oauthUserIds,proto3" json:"oauthUserIds,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CreateDate           *timestamp.Timestamp `protobuf:"bytes,10,opt,name=createDate,proto3" json:"createDate,omitempty"`
	UpdateDate           *timestamp.Timestamp `protobuf:"bytes,11,opt,name=updateDate,proto3" json:"updateDate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_uaa_6e45fa96551cfafa, []int{0}
}
func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (dst *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(dst, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *Account) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Account) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Account) GetPassword() []byte {
	if m != nil {
		return m.Password
	}
	return nil
}

func (m *Account) GetAccountExpired() bool {
	if m != nil {
		return m.AccountExpired
	}
	return false
}

func (m *Account) GetAccountLocked() bool {
	if m != nil {
		return m.AccountLocked
	}
	return false
}

func (m *Account) GetCredentialsExpired() bool {
	if m != nil {
		return m.CredentialsExpired
	}
	return false
}

func (m *Account) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *Account) GetOauthUserIds() map[uint32]string {
	if m != nil {
		return m.OauthUserIds
	}
	return nil
}

func (m *Account) GetCreateDate() *timestamp.Timestamp {
	if m != nil {
		return m.CreateDate
	}
	return nil
}

func (m *Account) GetUpdateDate() *timestamp.Timestamp {
	if m != nil {
		return m.UpdateDate
	}
	return nil
}

type GetAllResp struct {
	Accounts             []*Account `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetAllResp) Reset()         { *m = GetAllResp{} }
func (m *GetAllResp) String() string { return proto.CompactTextString(m) }
func (*GetAllResp) ProtoMessage()    {}
func (*GetAllResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_uaa_6e45fa96551cfafa, []int{1}
}
func (m *GetAllResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllResp.Unmarshal(m, b)
}
func (m *GetAllResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllResp.Marshal(b, m, deterministic)
}
func (dst *GetAllResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllResp.Merge(dst, src)
}
func (m *GetAllResp) XXX_Size() int {
	return xxx_messageInfo_GetAllResp.Size(m)
}
func (m *GetAllResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllResp proto.InternalMessageInfo

func (m *GetAllResp) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

type GetByUsernameReq struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByUsernameReq) Reset()         { *m = GetByUsernameReq{} }
func (m *GetByUsernameReq) String() string { return proto.CompactTextString(m) }
func (*GetByUsernameReq) ProtoMessage()    {}
func (*GetByUsernameReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_uaa_6e45fa96551cfafa, []int{2}
}
func (m *GetByUsernameReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByUsernameReq.Unmarshal(m, b)
}
func (m *GetByUsernameReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByUsernameReq.Marshal(b, m, deterministic)
}
func (dst *GetByUsernameReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByUsernameReq.Merge(dst, src)
}
func (m *GetByUsernameReq) XXX_Size() int {
	return xxx_messageInfo_GetByUsernameReq.Size(m)
}
func (m *GetByUsernameReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByUsernameReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetByUsernameReq proto.InternalMessageInfo

func (m *GetByUsernameReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type DeleteByUsernameReq struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteByUsernameReq) Reset()         { *m = DeleteByUsernameReq{} }
func (m *DeleteByUsernameReq) String() string { return proto.CompactTextString(m) }
func (*DeleteByUsernameReq) ProtoMessage()    {}
func (*DeleteByUsernameReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_uaa_6e45fa96551cfafa, []int{3}
}
func (m *DeleteByUsernameReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteByUsernameReq.Unmarshal(m, b)
}
func (m *DeleteByUsernameReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteByUsernameReq.Marshal(b, m, deterministic)
}
func (dst *DeleteByUsernameReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteByUsernameReq.Merge(dst, src)
}
func (m *DeleteByUsernameReq) XXX_Size() int {
	return xxx_messageInfo_DeleteByUsernameReq.Size(m)
}
func (m *DeleteByUsernameReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteByUsernameReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteByUsernameReq proto.InternalMessageInfo

func (m *DeleteByUsernameReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type RegisterReq struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string   `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Roles                []string `protobuf:"bytes,5,rep,name=roles,proto3" json:"roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterReq) Reset()         { *m = RegisterReq{} }
func (m *RegisterReq) String() string { return proto.CompactTextString(m) }
func (*RegisterReq) ProtoMessage()    {}
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_uaa_6e45fa96551cfafa, []int{4}
}
func (m *RegisterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterReq.Unmarshal(m, b)
}
func (m *RegisterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterReq.Marshal(b, m, deterministic)
}
func (dst *RegisterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterReq.Merge(dst, src)
}
func (m *RegisterReq) XXX_Size() int {
	return xxx_messageInfo_RegisterReq.Size(m)
}
func (m *RegisterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterReq proto.InternalMessageInfo

func (m *RegisterReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *RegisterReq) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

type VerifyPasswordReq struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyPasswordReq) Reset()         { *m = VerifyPasswordReq{} }
func (m *VerifyPasswordReq) String() string { return proto.CompactTextString(m) }
func (*VerifyPasswordReq) ProtoMessage()    {}
func (*VerifyPasswordReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_uaa_6e45fa96551cfafa, []int{5}
}
func (m *VerifyPasswordReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyPasswordReq.Unmarshal(m, b)
}
func (m *VerifyPasswordReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyPasswordReq.Marshal(b, m, deterministic)
}
func (dst *VerifyPasswordReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyPasswordReq.Merge(dst, src)
}
func (m *VerifyPasswordReq) XXX_Size() int {
	return xxx_messageInfo_VerifyPasswordReq.Size(m)
}
func (m *VerifyPasswordReq) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyPasswordReq.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyPasswordReq proto.InternalMessageInfo

func (m *VerifyPasswordReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *VerifyPasswordReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ChangePasswordReq struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	OldPassword          string   `protobuf:"bytes,2,opt,name=oldPassword,proto3" json:"oldPassword,omitempty"`
	NewPassword          string   `protobuf:"bytes,3,opt,name=newPassword,proto3" json:"newPassword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePasswordReq) Reset()         { *m = ChangePasswordReq{} }
func (m *ChangePasswordReq) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordReq) ProtoMessage()    {}
func (*ChangePasswordReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_uaa_6e45fa96551cfafa, []int{6}
}
func (m *ChangePasswordReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordReq.Unmarshal(m, b)
}
func (m *ChangePasswordReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordReq.Marshal(b, m, deterministic)
}
func (dst *ChangePasswordReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordReq.Merge(dst, src)
}
func (m *ChangePasswordReq) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordReq.Size(m)
}
func (m *ChangePasswordReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordReq.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordReq proto.InternalMessageInfo

func (m *ChangePasswordReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ChangePasswordReq) GetOldPassword() string {
	if m != nil {
		return m.OldPassword
	}
	return ""
}

func (m *ChangePasswordReq) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

func init() {
	proto.RegisterType((*Account)(nil), "com.teddy.srv.uaa.Account")
	proto.RegisterMapType((map[uint32]string)(nil), "com.teddy.srv.uaa.Account.OauthUserIdsEntry")
	proto.RegisterType((*GetAllResp)(nil), "com.teddy.srv.uaa.GetAllResp")
	proto.RegisterType((*GetByUsernameReq)(nil), "com.teddy.srv.uaa.GetByUsernameReq")
	proto.RegisterType((*DeleteByUsernameReq)(nil), "com.teddy.srv.uaa.DeleteByUsernameReq")
	proto.RegisterType((*RegisterReq)(nil), "com.teddy.srv.uaa.RegisterReq")
	proto.RegisterType((*VerifyPasswordReq)(nil), "com.teddy.srv.uaa.VerifyPasswordReq")
	proto.RegisterType((*ChangePasswordReq)(nil), "com.teddy.srv.uaa.ChangePasswordReq")
	proto.RegisterEnum("com.teddy.srv.uaa.OAuthType", OAuthType_name, OAuthType_value)
}

func init() { proto.RegisterFile("proto/uaa.proto", fileDescriptor_uaa_6e45fa96551cfafa) }

var fileDescriptor_uaa_6e45fa96551cfafa = []byte{
	// 687 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x94, 0x6d, 0x4f, 0xdb, 0x30,
	0x10, 0xc7, 0xe9, 0x73, 0xb8, 0x02, 0x4b, 0xbd, 0x69, 0x8a, 0x22, 0x6d, 0x42, 0x19, 0x42, 0xd3,
	0x34, 0xb9, 0x1a, 0x48, 0xd3, 0xc4, 0x5e, 0x4c, 0x01, 0x32, 0x40, 0xa0, 0xb5, 0x64, 0x61, 0x48,
	0x7b, 0x17, 0x1a, 0xd3, 0x46, 0xa4, 0x71, 0x16, 0x3b, 0xb0, 0x7e, 0x82, 0xed, 0x83, 0xee, 0x83,
	0xcc, 0x71, 0xfa, 0x14, 0x1a, 0x56, 0xa4, 0xbd, 0x68, 0x6b, 0xdf, 0xfd, 0xef, 0x9f, 0xb3, 0xef,
	0xd7, 0xc0, 0x93, 0x28, 0xa6, 0x9c, 0xb6, 0x13, 0xd7, 0xc5, 0x72, 0x85, 0x5a, 0x3d, 0x3a, 0xc4,
	0x9c, 0x78, 0xde, 0x08, 0xb3, 0xf8, 0x16, 0x8b, 0x84, 0xbe, 0xdb, 0xf7, 0xf9, 0x20, 0xb9, 0xc2,
	0x22, 0xd3, 0xee, 0xd3, 0xc0, 0x0d, 0xfb, 0x6d, 0xa9, 0xbd, 0x4a, 0xae, 0xdb, 0x11, 0x1f, 0x45,
	0x84, 0xb5, 0xc9, 0x50, 0x2c, 0xb2, 0xef, 0xcc, 0x47, 0xff, 0xb8, 0xbc, 0x88, 0xfb, 0x43, 0xc2,
	0xb8, 0x3b, 0x8c, 0x66, 0xab, 0xac, 0xd8, 0xf8, 0x5d, 0x85, 0x86, 0xd9, 0xeb, 0xd1, 0x24, 0xe4,
	0x48, 0x85, 0x4a, 0xe2, 0x7b, 0x5a, 0x69, 0xb3, 0xf4, 0x7a, 0xd5, 0x4e, 0x97, 0x48, 0x07, 0x25,
	0x61, 0x24, 0x0e, 0xdd, 0x21, 0xd1, 0xca, 0x32, 0x3c, 0xdd, 0xa3, 0x67, 0x50, 0x23, 0x43, 0xd7,
	0x0f, 0xb4, 0x8a, 0x4c, 0x64, 0x9b, 0xb4, 0x22, 0x72, 0x19, 0xbb, 0xa3, 0xb1, 0xa7, 0x55, 0x45,
	0x62, 0xcd, 0x9e, 0xee, 0xd1, 0x36, 0x6c, 0xb8, 0xd9, 0xa3, 0xac, 0x9f, 0x91, 0x1f, 0x13, 0x4f,
	0xab, 0x09, 0x85, 0x62, 0xdf, 0x8b, 0xa2, 0x2d, 0x58, 0x1f, 0x47, 0xce, 0x68, 0xef, 0x46, 0xc8,
	0xea, 0x52, 0x96, 0x0f, 0x22, 0x0c, 0xa8, 0x27, 0xd4, 0x24, 0xe4, 0xbe, 0x1b, 0xb0, 0x89, 0x63,
	0x43, 0x4a, 0x0b, 0x32, 0x69, 0xbf, 0x31, 0x0d, 0x08, 0xd3, 0x94, 0xcd, 0x4a, 0xda, 0xaf, 0xdc,
	0xa0, 0x2e, 0xac, 0x51, 0x37, 0xe1, 0x83, 0x0b, 0x71, 0xac, 0x13, 0x8f, 0x69, 0xab, 0x22, 0xd9,
	0xdc, 0x79, 0x8b, 0x17, 0x66, 0x83, 0xc7, 0xb7, 0x84, 0x3b, 0x73, 0x72, 0x2b, 0xe4, 0xf1, 0xc8,
	0xce, 0x39, 0xa0, 0x3d, 0x00, 0xf1, 0x74, 0x97, 0x93, 0x43, 0xf1, 0xd1, 0x40, 0xf4, 0xd3, 0xdc,
	0xd1, 0x71, 0x9f, 0xd2, 0x7e, 0x40, 0xf0, 0x64, 0x30, 0xd8, 0x99, 0xcc, 0xc1, 0x9e, 0x53, 0xa7,
	0xb5, 0x49, 0xe4, 0x4d, 0x6a, 0x9b, 0xcb, 0x6b, 0x67, 0x6a, 0xfd, 0x13, 0xb4, 0x16, 0x5a, 0x4b,
	0x47, 0x7a, 0x43, 0x46, 0x72, 0xa4, 0xeb, 0x76, 0xba, 0x4c, 0xaf, 0xe1, 0xd6, 0x0d, 0x92, 0xc9,
	0x3c, 0xb3, 0xcd, 0x5e, 0xf9, 0x43, 0xc9, 0x38, 0x04, 0x38, 0x22, 0xdc, 0x0c, 0x02, 0x9b, 0xb0,
	0x08, 0xbd, 0x07, 0x65, 0x7c, 0xdf, 0x4c, 0x94, 0x57, 0x64, 0x23, 0x0f, 0x5e, 0x8a, 0x3d, 0xd5,
	0x1a, 0x18, 0x54, 0xe1, 0xb2, 0x3f, 0xba, 0x18, 0x73, 0x62, 0x93, 0x1f, 0x39, 0x8c, 0x4a, 0x79,
	0x8c, 0x8c, 0x77, 0xf0, 0xf4, 0x90, 0x04, 0x84, 0x93, 0xc7, 0x97, 0xfc, 0x2a, 0x41, 0xd3, 0x26,
	0x7d, 0x9f, 0x71, 0x12, 0x2f, 0xd1, 0xe6, 0x78, 0x1c, 0x13, 0x3c, 0xe5, 0xb1, 0x98, 0x60, 0x11,
	0x8d, 0x06, 0x34, 0x24, 0x12, 0x5f, 0x11, 0x95, 0x9b, 0x19, 0x3d, 0xb5, 0x39, 0x7a, 0x8c, 0x53,
	0x68, 0x7d, 0x23, 0xb1, 0x7f, 0x3d, 0xea, 0x8e, 0x3d, 0xff, 0xa3, 0x1d, 0x83, 0x41, 0xeb, 0x60,
	0x20, 0xfe, 0xbd, 0xe4, 0xb1, 0x66, 0x9b, 0xd0, 0xa4, 0x81, 0xd7, 0xcd, 0xfb, 0xcd, 0x87, 0x52,
	0x45, 0x48, 0xee, 0xa6, 0x8a, 0xec, 0x9c, 0xf3, 0xa1, 0x37, 0x5d, 0x58, 0xed, 0x98, 0x82, 0x1a,
	0x47, 0xbc, 0x27, 0x10, 0x40, 0xfd, 0xa8, 0xd3, 0x39, 0x3a, 0xb3, 0xd4, 0x95, 0x74, 0x7d, 0x69,
	0x1d, 0x1c, 0x9b, 0x8e, 0x5a, 0x42, 0x75, 0x28, 0x9f, 0x9f, 0xab, 0x65, 0xa4, 0x40, 0xf5, 0xeb,
	0xc9, 0x17, 0x53, 0xad, 0xa0, 0x35, 0x50, 0x3e, 0x9b, 0x07, 0xd6, 0x7e, 0xa7, 0x73, 0xaa, 0x56,
	0x51, 0x13, 0x1a, 0xce, 0xe5, 0x89, 0xe3, 0x58, 0xb6, 0x5a, 0xdb, 0xf9, 0x53, 0x81, 0xca, 0x85,
	0x69, 0x22, 0x53, 0x98, 0x49, 0x9c, 0xd0, 0xf3, 0x05, 0x82, 0xad, 0xf4, 0xf5, 0xa5, 0xbf, 0x28,
	0x00, 0x6a, 0x46, 0xa0, 0xb1, 0x82, 0x6c, 0x58, 0xcf, 0xb1, 0x84, 0x5e, 0x15, 0x57, 0xe4, 0xd0,
	0xd1, 0xff, 0xc1, 0xa9, 0xf0, 0x74, 0x40, 0xbd, 0xcf, 0x1b, 0xda, 0x2e, 0xa8, 0x28, 0x80, 0x52,
	0x7f, 0xe0, 0x20, 0xc2, 0xf5, 0x18, 0x94, 0x09, 0x91, 0xe8, 0x65, 0x81, 0xdb, 0x1c, 0xae, 0x4b,
	0xfb, 0xdb, 0xc8, 0x23, 0x85, 0xb6, 0x0a, 0xf4, 0x0b, 0xd4, 0x2d, 0x71, 0xed, 0xc2, 0x46, 0x9e,
	0xad, 0x42, 0xd7, 0x05, 0xfc, 0x1e, 0x3e, 0xf1, 0x7e, 0xe3, 0x7b, 0x2d, 0x8b, 0xd5, 0xe5, 0xcf,
	0xee, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x37, 0x94, 0xc3, 0x0b, 0xe0, 0x06, 0x00, 0x00,
}
