// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/message.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/empty"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type InBoxEntry struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Topic                string   `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Cotent               string   `protobuf:"bytes,3,opt,name=cotent,proto3" json:"cotent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InBoxEntry) Reset()         { *m = InBoxEntry{} }
func (m *InBoxEntry) String() string { return proto.CompactTextString(m) }
func (*InBoxEntry) ProtoMessage()    {}
func (*InBoxEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_b7c166e860187578, []int{0}
}
func (m *InBoxEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InBoxEntry.Unmarshal(m, b)
}
func (m *InBoxEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InBoxEntry.Marshal(b, m, deterministic)
}
func (dst *InBoxEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InBoxEntry.Merge(dst, src)
}
func (m *InBoxEntry) XXX_Size() int {
	return xxx_messageInfo_InBoxEntry.Size(m)
}
func (m *InBoxEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_InBoxEntry.DiscardUnknown(m)
}

var xxx_messageInfo_InBoxEntry proto.InternalMessageInfo

func (m *InBoxEntry) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *InBoxEntry) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *InBoxEntry) GetCotent() string {
	if m != nil {
		return m.Cotent
	}
	return ""
}

type NotifyEntry struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Detail               string   `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyEntry) Reset()         { *m = NotifyEntry{} }
func (m *NotifyEntry) String() string { return proto.CompactTextString(m) }
func (*NotifyEntry) ProtoMessage()    {}
func (*NotifyEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_b7c166e860187578, []int{1}
}
func (m *NotifyEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyEntry.Unmarshal(m, b)
}
func (m *NotifyEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyEntry.Marshal(b, m, deterministic)
}
func (dst *NotifyEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyEntry.Merge(dst, src)
}
func (m *NotifyEntry) XXX_Size() int {
	return xxx_messageInfo_NotifyEntry.Size(m)
}
func (m *NotifyEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyEntry.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyEntry proto.InternalMessageInfo

func (m *NotifyEntry) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *NotifyEntry) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

type SendEmailReq struct {
	Email                string               `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Topic                string               `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Cotent               string               `protobuf:"bytes,3,opt,name=cotent,proto3" json:"cotent,omitempty"`
	Until                *timestamp.Timestamp `protobuf:"bytes,4,opt,name=until,proto3" json:"until,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SendEmailReq) Reset()         { *m = SendEmailReq{} }
func (m *SendEmailReq) String() string { return proto.CompactTextString(m) }
func (*SendEmailReq) ProtoMessage()    {}
func (*SendEmailReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_b7c166e860187578, []int{2}
}
func (m *SendEmailReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendEmailReq.Unmarshal(m, b)
}
func (m *SendEmailReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendEmailReq.Marshal(b, m, deterministic)
}
func (dst *SendEmailReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendEmailReq.Merge(dst, src)
}
func (m *SendEmailReq) XXX_Size() int {
	return xxx_messageInfo_SendEmailReq.Size(m)
}
func (m *SendEmailReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SendEmailReq.DiscardUnknown(m)
}

var xxx_messageInfo_SendEmailReq proto.InternalMessageInfo

func (m *SendEmailReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SendEmailReq) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *SendEmailReq) GetCotent() string {
	if m != nil {
		return m.Cotent
	}
	return ""
}

func (m *SendEmailReq) GetUntil() *timestamp.Timestamp {
	if m != nil {
		return m.Until
	}
	return nil
}

type SendInBoxReq struct {
	Username             string               `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Topic                string               `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Content              string               `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Until                *timestamp.Timestamp `protobuf:"bytes,4,opt,name=until,proto3" json:"until,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SendInBoxReq) Reset()         { *m = SendInBoxReq{} }
func (m *SendInBoxReq) String() string { return proto.CompactTextString(m) }
func (*SendInBoxReq) ProtoMessage()    {}
func (*SendInBoxReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_b7c166e860187578, []int{3}
}
func (m *SendInBoxReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendInBoxReq.Unmarshal(m, b)
}
func (m *SendInBoxReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendInBoxReq.Marshal(b, m, deterministic)
}
func (dst *SendInBoxReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendInBoxReq.Merge(dst, src)
}
func (m *SendInBoxReq) XXX_Size() int {
	return xxx_messageInfo_SendInBoxReq.Size(m)
}
func (m *SendInBoxReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SendInBoxReq.DiscardUnknown(m)
}

var xxx_messageInfo_SendInBoxReq proto.InternalMessageInfo

func (m *SendInBoxReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *SendInBoxReq) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *SendInBoxReq) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *SendInBoxReq) GetUntil() *timestamp.Timestamp {
	if m != nil {
		return m.Until
	}
	return nil
}

type SendNotifyReq struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Topic                string   `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Detail               string   `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendNotifyReq) Reset()         { *m = SendNotifyReq{} }
func (m *SendNotifyReq) String() string { return proto.CompactTextString(m) }
func (*SendNotifyReq) ProtoMessage()    {}
func (*SendNotifyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_b7c166e860187578, []int{4}
}
func (m *SendNotifyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendNotifyReq.Unmarshal(m, b)
}
func (m *SendNotifyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendNotifyReq.Marshal(b, m, deterministic)
}
func (dst *SendNotifyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendNotifyReq.Merge(dst, src)
}
func (m *SendNotifyReq) XXX_Size() int {
	return xxx_messageInfo_SendNotifyReq.Size(m)
}
func (m *SendNotifyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SendNotifyReq.DiscardUnknown(m)
}

var xxx_messageInfo_SendNotifyReq proto.InternalMessageInfo

func (m *SendNotifyReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *SendNotifyReq) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *SendNotifyReq) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

type SendSMSReq struct {
	PhoneNumber          string               `protobuf:"bytes,1,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	Content              string               `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Until                *timestamp.Timestamp `protobuf:"bytes,3,opt,name=until,proto3" json:"until,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SendSMSReq) Reset()         { *m = SendSMSReq{} }
func (m *SendSMSReq) String() string { return proto.CompactTextString(m) }
func (*SendSMSReq) ProtoMessage()    {}
func (*SendSMSReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_b7c166e860187578, []int{5}
}
func (m *SendSMSReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendSMSReq.Unmarshal(m, b)
}
func (m *SendSMSReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendSMSReq.Marshal(b, m, deterministic)
}
func (dst *SendSMSReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendSMSReq.Merge(dst, src)
}
func (m *SendSMSReq) XXX_Size() int {
	return xxx_messageInfo_SendSMSReq.Size(m)
}
func (m *SendSMSReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SendSMSReq.DiscardUnknown(m)
}

var xxx_messageInfo_SendSMSReq proto.InternalMessageInfo

func (m *SendSMSReq) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *SendSMSReq) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *SendSMSReq) GetUntil() *timestamp.Timestamp {
	if m != nil {
		return m.Until
	}
	return nil
}

type GetInBoxReq struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInBoxReq) Reset()         { *m = GetInBoxReq{} }
func (m *GetInBoxReq) String() string { return proto.CompactTextString(m) }
func (*GetInBoxReq) ProtoMessage()    {}
func (*GetInBoxReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_b7c166e860187578, []int{6}
}
func (m *GetInBoxReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInBoxReq.Unmarshal(m, b)
}
func (m *GetInBoxReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInBoxReq.Marshal(b, m, deterministic)
}
func (dst *GetInBoxReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInBoxReq.Merge(dst, src)
}
func (m *GetInBoxReq) XXX_Size() int {
	return xxx_messageInfo_GetInBoxReq.Size(m)
}
func (m *GetInBoxReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInBoxReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetInBoxReq proto.InternalMessageInfo

func (m *GetInBoxReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type GetNotifyReq struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNotifyReq) Reset()         { *m = GetNotifyReq{} }
func (m *GetNotifyReq) String() string { return proto.CompactTextString(m) }
func (*GetNotifyReq) ProtoMessage()    {}
func (*GetNotifyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_b7c166e860187578, []int{7}
}
func (m *GetNotifyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNotifyReq.Unmarshal(m, b)
}
func (m *GetNotifyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNotifyReq.Marshal(b, m, deterministic)
}
func (dst *GetNotifyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNotifyReq.Merge(dst, src)
}
func (m *GetNotifyReq) XXX_Size() int {
	return xxx_messageInfo_GetNotifyReq.Size(m)
}
func (m *GetNotifyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNotifyReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetNotifyReq proto.InternalMessageInfo

func (m *GetNotifyReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func init() {
	proto.RegisterType((*InBoxEntry)(nil), "com.teddy.srv.notify.InBoxEntry")
	proto.RegisterType((*NotifyEntry)(nil), "com.teddy.srv.notify.NotifyEntry")
	proto.RegisterType((*SendEmailReq)(nil), "com.teddy.srv.notify.SendEmailReq")
	proto.RegisterType((*SendInBoxReq)(nil), "com.teddy.srv.notify.SendInBoxReq")
	proto.RegisterType((*SendNotifyReq)(nil), "com.teddy.srv.notify.SendNotifyReq")
	proto.RegisterType((*SendSMSReq)(nil), "com.teddy.srv.notify.SendSMSReq")
	proto.RegisterType((*GetInBoxReq)(nil), "com.teddy.srv.notify.GetInBoxReq")
	proto.RegisterType((*GetNotifyReq)(nil), "com.teddy.srv.notify.GetNotifyReq")
}

func init() { proto.RegisterFile("proto/message.proto", fileDescriptor_message_b7c166e860187578) }

var fileDescriptor_message_b7c166e860187578 = []byte{
	// 476 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x94, 0xcf, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0x97, 0x96, 0xae, 0xeb, 0xeb, 0xe0, 0x60, 0xa6, 0xa9, 0xca, 0xa9, 0x98, 0x0b, 0x70,
	0x70, 0xa6, 0xed, 0xb8, 0xdb, 0xa4, 0x08, 0x0d, 0xb4, 0x1d, 0x1a, 0x84, 0x04, 0xb7, 0x34, 0xf1,
	0xb2, 0x48, 0x8d, 0x1d, 0x12, 0x07, 0x11, 0xce, 0x1c, 0xf9, 0x23, 0xf9, 0x53, 0xf0, 0xaf, 0xa4,
	0x01, 0x96, 0xd0, 0xf5, 0xd2, 0xfa, 0xbd, 0xf8, 0x7d, 0xfc, 0x7d, 0xdf, 0x17, 0x07, 0x9e, 0xe7,
	0x05, 0x17, 0xdc, 0xcb, 0x68, 0x59, 0x86, 0x09, 0x25, 0x3a, 0x42, 0x27, 0x11, 0xcf, 0x88, 0xa0,
	0x71, 0x5c, 0x93, 0xb2, 0xf8, 0x4a, 0x18, 0x17, 0xe9, 0x5d, 0xed, 0x5e, 0x24, 0xa9, 0xb8, 0xaf,
	0xd6, 0x44, 0x3e, 0xf4, 0x12, 0xbe, 0x09, 0x59, 0xe2, 0xe9, 0xed, 0xeb, 0xea, 0xce, 0xcb, 0x45,
	0x9d, 0xd3, 0xd2, 0xa3, 0x99, 0x5c, 0x98, 0x5f, 0x83, 0x72, 0x2f, 0xff, 0x5f, 0x24, 0x52, 0x79,
	0xba, 0x08, 0xb3, 0x7c, 0xbb, 0x32, 0xc5, 0xf8, 0x1d, 0xc0, 0x35, 0xbb, 0xe2, 0xdf, 0x7c, 0x26,
	0x8a, 0x1a, 0x3d, 0x83, 0x51, 0x1a, 0x2f, 0x9c, 0xa5, 0xf3, 0x6a, 0xb6, 0x92, 0x2b, 0x74, 0x02,
	0x13, 0xc1, 0xf3, 0x34, 0x5a, 0x8c, 0x74, 0xca, 0x04, 0xe8, 0x14, 0x0e, 0x23, 0x2e, 0x28, 0x13,
	0x8b, 0xb1, 0x4e, 0xdb, 0x08, 0x5f, 0xc2, 0xfc, 0x56, 0xf7, 0x61, 0x60, 0x6d, 0xb1, 0xf3, 0x57,
	0x71, 0x4c, 0x45, 0x98, 0x6e, 0x2c, 0xd3, 0x46, 0xf8, 0x87, 0x03, 0xc7, 0x01, 0x65, 0xb1, 0x9f,
	0xc9, 0x68, 0x45, 0xbf, 0xa8, 0x72, 0xaa, 0xd6, 0x4d, 0xb9, 0x0e, 0x1e, 0xa7, 0x08, 0x9d, 0xc1,
	0xa4, 0x62, 0x42, 0x32, 0x9e, 0xc8, 0xf4, 0xfc, 0xdc, 0x25, 0x09, 0xe7, 0xc9, 0xc6, 0xce, 0x40,
	0xfa, 0x43, 0x3e, 0x34, 0x76, 0xac, 0xcc, 0x46, 0xfc, 0xd3, 0xca, 0xd0, 0xa6, 0x28, 0x19, 0x2e,
	0x1c, 0x55, 0x25, 0x2d, 0x58, 0x98, 0x51, 0xab, 0xa4, 0x8d, 0x7b, 0xc4, 0x2c, 0x60, 0x1a, 0x71,
	0xd6, 0x51, 0xd3, 0x84, 0x7b, 0xc8, 0xf9, 0x04, 0x4f, 0x95, 0x1a, 0x63, 0xeb, 0x7e, 0x72, 0xb6,
	0x86, 0x8f, 0xff, 0x30, 0xfc, 0x3b, 0x80, 0x42, 0x07, 0x37, 0x81, 0xe2, 0x2e, 0x61, 0x9e, 0xdf,
	0x73, 0x46, 0x6f, 0xab, 0x6c, 0x4d, 0x0b, 0x8b, 0xee, 0xa6, 0xba, 0x6d, 0x8d, 0x7a, 0xda, 0x1a,
	0xef, 0xda, 0xd6, 0x6b, 0x98, 0xbf, 0xa5, 0x62, 0x17, 0x8f, 0xf1, 0x1b, 0x38, 0x96, 0x5b, 0x77,
	0x32, 0xe0, 0xfc, 0xd7, 0x18, 0xa6, 0x37, 0xe6, 0x9a, 0xa1, 0x6b, 0x98, 0xb5, 0xaf, 0x13, 0xc2,
	0xe4, 0xa1, 0xeb, 0x46, 0xba, 0xef, 0x9b, 0x7b, 0xfa, 0x8f, 0x6c, 0x5f, 0x5d, 0x32, 0x7c, 0xd0,
	0xa0, 0xb4, 0xdc, 0x21, 0x54, 0xd3, 0xcf, 0x00, 0xea, 0xbd, 0x31, 0xdd, 0xb4, 0x83, 0x5e, 0xf6,
	0xb3, 0xda, 0x86, 0x07, 0x60, 0x3e, 0x4c, 0xed, 0x04, 0xd1, 0xb2, 0x9f, 0x64, 0x06, 0x3c, 0x80,
	0x09, 0xe0, 0xa8, 0x19, 0x06, 0x7a, 0xf1, 0x30, 0xa7, 0x33, 0x2c, 0xb7, 0xe7, 0xa8, 0xed, 0x57,
	0x04, 0x1f, 0x9c, 0x39, 0xe8, 0x23, 0xcc, 0xda, 0xb1, 0xf5, 0x79, 0xd6, 0x9d, 0xab, 0xdb, 0x73,
	0x72, 0xe7, 0x83, 0xa2, 0xb8, 0x57, 0xd3, 0xcf, 0x13, 0xd3, 0xc0, 0xa1, 0xfe, 0xbb, 0xf8, 0x1d,
	0x00, 0x00, 0xff, 0xff, 0x5a, 0xaf, 0x4e, 0xaf, 0x5e, 0x05, 0x00, 0x00,
}
