// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/message.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/empty"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type InBoxItem struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Topic                string               `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Content              string               `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	From                 string               `protobuf:"bytes,4,opt,name=from,proto3" json:"from,omitempty"`
	Type                 uint32               `protobuf:"varint,5,opt,name=Type,proto3" json:"Type,omitempty"`
	Unread               bool                 `protobuf:"varint,6,opt,name=unread,proto3" json:"unread,omitempty"`
	SendTime             *timestamp.Timestamp `protobuf:"bytes,7,opt,name=sendTime,proto3" json:"sendTime,omitempty"`
	ReadTime             *timestamp.Timestamp `protobuf:"bytes,8,opt,name=ReadTime,proto3" json:"ReadTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *InBoxItem) Reset()         { *m = InBoxItem{} }
func (m *InBoxItem) String() string { return proto.CompactTextString(m) }
func (*InBoxItem) ProtoMessage()    {}
func (*InBoxItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_3a76f83c53f6b8b5, []int{0}
}
func (m *InBoxItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InBoxItem.Unmarshal(m, b)
}
func (m *InBoxItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InBoxItem.Marshal(b, m, deterministic)
}
func (dst *InBoxItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InBoxItem.Merge(dst, src)
}
func (m *InBoxItem) XXX_Size() int {
	return xxx_messageInfo_InBoxItem.Size(m)
}
func (m *InBoxItem) XXX_DiscardUnknown() {
	xxx_messageInfo_InBoxItem.DiscardUnknown(m)
}

var xxx_messageInfo_InBoxItem proto.InternalMessageInfo

func (m *InBoxItem) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *InBoxItem) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *InBoxItem) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *InBoxItem) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *InBoxItem) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *InBoxItem) GetUnread() bool {
	if m != nil {
		return m.Unread
	}
	return false
}

func (m *InBoxItem) GetSendTime() *timestamp.Timestamp {
	if m != nil {
		return m.SendTime
	}
	return nil
}

func (m *InBoxItem) GetReadTime() *timestamp.Timestamp {
	if m != nil {
		return m.ReadTime
	}
	return nil
}

type NotifyItem struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Detail               string   `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyItem) Reset()         { *m = NotifyItem{} }
func (m *NotifyItem) String() string { return proto.CompactTextString(m) }
func (*NotifyItem) ProtoMessage()    {}
func (*NotifyItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_3a76f83c53f6b8b5, []int{1}
}
func (m *NotifyItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyItem.Unmarshal(m, b)
}
func (m *NotifyItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyItem.Marshal(b, m, deterministic)
}
func (dst *NotifyItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyItem.Merge(dst, src)
}
func (m *NotifyItem) XXX_Size() int {
	return xxx_messageInfo_NotifyItem.Size(m)
}
func (m *NotifyItem) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyItem.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyItem proto.InternalMessageInfo

func (m *NotifyItem) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *NotifyItem) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

type SendEmailReq struct {
	Email                string               `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Topic                string               `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Cotent               string               `protobuf:"bytes,3,opt,name=cotent,proto3" json:"cotent,omitempty"`
	Until                *timestamp.Timestamp `protobuf:"bytes,4,opt,name=until,proto3" json:"until,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SendEmailReq) Reset()         { *m = SendEmailReq{} }
func (m *SendEmailReq) String() string { return proto.CompactTextString(m) }
func (*SendEmailReq) ProtoMessage()    {}
func (*SendEmailReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_3a76f83c53f6b8b5, []int{2}
}
func (m *SendEmailReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendEmailReq.Unmarshal(m, b)
}
func (m *SendEmailReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendEmailReq.Marshal(b, m, deterministic)
}
func (dst *SendEmailReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendEmailReq.Merge(dst, src)
}
func (m *SendEmailReq) XXX_Size() int {
	return xxx_messageInfo_SendEmailReq.Size(m)
}
func (m *SendEmailReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SendEmailReq.DiscardUnknown(m)
}

var xxx_messageInfo_SendEmailReq proto.InternalMessageInfo

func (m *SendEmailReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SendEmailReq) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *SendEmailReq) GetCotent() string {
	if m != nil {
		return m.Cotent
	}
	return ""
}

func (m *SendEmailReq) GetUntil() *timestamp.Timestamp {
	if m != nil {
		return m.Until
	}
	return nil
}

type SendInBoxReq struct {
	Uid                  string               `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Topic                string               `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Content              string               `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	From                 string               `protobuf:"bytes,4,opt,name=from,proto3" json:"from,omitempty"`
	Type                 uint32               `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"`
	SendTime             *timestamp.Timestamp `protobuf:"bytes,6,opt,name=sendTime,proto3" json:"sendTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SendInBoxReq) Reset()         { *m = SendInBoxReq{} }
func (m *SendInBoxReq) String() string { return proto.CompactTextString(m) }
func (*SendInBoxReq) ProtoMessage()    {}
func (*SendInBoxReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_3a76f83c53f6b8b5, []int{3}
}
func (m *SendInBoxReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendInBoxReq.Unmarshal(m, b)
}
func (m *SendInBoxReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendInBoxReq.Marshal(b, m, deterministic)
}
func (dst *SendInBoxReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendInBoxReq.Merge(dst, src)
}
func (m *SendInBoxReq) XXX_Size() int {
	return xxx_messageInfo_SendInBoxReq.Size(m)
}
func (m *SendInBoxReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SendInBoxReq.DiscardUnknown(m)
}

var xxx_messageInfo_SendInBoxReq proto.InternalMessageInfo

func (m *SendInBoxReq) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *SendInBoxReq) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *SendInBoxReq) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *SendInBoxReq) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *SendInBoxReq) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *SendInBoxReq) GetSendTime() *timestamp.Timestamp {
	if m != nil {
		return m.SendTime
	}
	return nil
}

type SendNotifyReq struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Topic                string   `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Detail               string   `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendNotifyReq) Reset()         { *m = SendNotifyReq{} }
func (m *SendNotifyReq) String() string { return proto.CompactTextString(m) }
func (*SendNotifyReq) ProtoMessage()    {}
func (*SendNotifyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_3a76f83c53f6b8b5, []int{4}
}
func (m *SendNotifyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendNotifyReq.Unmarshal(m, b)
}
func (m *SendNotifyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendNotifyReq.Marshal(b, m, deterministic)
}
func (dst *SendNotifyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendNotifyReq.Merge(dst, src)
}
func (m *SendNotifyReq) XXX_Size() int {
	return xxx_messageInfo_SendNotifyReq.Size(m)
}
func (m *SendNotifyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SendNotifyReq.DiscardUnknown(m)
}

var xxx_messageInfo_SendNotifyReq proto.InternalMessageInfo

func (m *SendNotifyReq) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *SendNotifyReq) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *SendNotifyReq) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

type SendSMSReq struct {
	PhoneNumber          string   `protobuf:"bytes,1,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendSMSReq) Reset()         { *m = SendSMSReq{} }
func (m *SendSMSReq) String() string { return proto.CompactTextString(m) }
func (*SendSMSReq) ProtoMessage()    {}
func (*SendSMSReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_3a76f83c53f6b8b5, []int{5}
}
func (m *SendSMSReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendSMSReq.Unmarshal(m, b)
}
func (m *SendSMSReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendSMSReq.Marshal(b, m, deterministic)
}
func (dst *SendSMSReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendSMSReq.Merge(dst, src)
}
func (m *SendSMSReq) XXX_Size() int {
	return xxx_messageInfo_SendSMSReq.Size(m)
}
func (m *SendSMSReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SendSMSReq.DiscardUnknown(m)
}

var xxx_messageInfo_SendSMSReq proto.InternalMessageInfo

func (m *SendSMSReq) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *SendSMSReq) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type GetInBoxReq struct {
	Page                 uint32   `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size                 uint32   `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Type                 uint32   `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Uid                  string   `protobuf:"bytes,4,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInBoxReq) Reset()         { *m = GetInBoxReq{} }
func (m *GetInBoxReq) String() string { return proto.CompactTextString(m) }
func (*GetInBoxReq) ProtoMessage()    {}
func (*GetInBoxReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_3a76f83c53f6b8b5, []int{6}
}
func (m *GetInBoxReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInBoxReq.Unmarshal(m, b)
}
func (m *GetInBoxReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInBoxReq.Marshal(b, m, deterministic)
}
func (dst *GetInBoxReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInBoxReq.Merge(dst, src)
}
func (m *GetInBoxReq) XXX_Size() int {
	return xxx_messageInfo_GetInBoxReq.Size(m)
}
func (m *GetInBoxReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInBoxReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetInBoxReq proto.InternalMessageInfo

func (m *GetInBoxReq) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetInBoxReq) GetSize() uint32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *GetInBoxReq) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *GetInBoxReq) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type GetNotifyReq struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNotifyReq) Reset()         { *m = GetNotifyReq{} }
func (m *GetNotifyReq) String() string { return proto.CompactTextString(m) }
func (*GetNotifyReq) ProtoMessage()    {}
func (*GetNotifyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_3a76f83c53f6b8b5, []int{7}
}
func (m *GetNotifyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNotifyReq.Unmarshal(m, b)
}
func (m *GetNotifyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNotifyReq.Marshal(b, m, deterministic)
}
func (dst *GetNotifyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNotifyReq.Merge(dst, src)
}
func (m *GetNotifyReq) XXX_Size() int {
	return xxx_messageInfo_GetNotifyReq.Size(m)
}
func (m *GetNotifyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNotifyReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetNotifyReq proto.InternalMessageInfo

func (m *GetNotifyReq) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func init() {
	proto.RegisterType((*InBoxItem)(nil), "com.teddy.srv.notify.InBoxItem")
	proto.RegisterType((*NotifyItem)(nil), "com.teddy.srv.notify.NotifyItem")
	proto.RegisterType((*SendEmailReq)(nil), "com.teddy.srv.notify.SendEmailReq")
	proto.RegisterType((*SendInBoxReq)(nil), "com.teddy.srv.notify.SendInBoxReq")
	proto.RegisterType((*SendNotifyReq)(nil), "com.teddy.srv.notify.SendNotifyReq")
	proto.RegisterType((*SendSMSReq)(nil), "com.teddy.srv.notify.SendSMSReq")
	proto.RegisterType((*GetInBoxReq)(nil), "com.teddy.srv.notify.GetInBoxReq")
	proto.RegisterType((*GetNotifyReq)(nil), "com.teddy.srv.notify.GetNotifyReq")
}

func init() { proto.RegisterFile("proto/message.proto", fileDescriptor_message_3a76f83c53f6b8b5) }

var fileDescriptor_message_3a76f83c53f6b8b5 = []byte{
	// 569 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xad, 0x9b, 0xef, 0x49, 0x8b, 0xd0, 0x52, 0x55, 0x96, 0x2f, 0x84, 0xe5, 0xc2, 0xc9, 0xa9,
	0x5a, 0x89, 0x03, 0xdc, 0x2a, 0x45, 0x10, 0xa1, 0x16, 0xc9, 0x09, 0x17, 0x38, 0x25, 0xf1, 0xc6,
	0xb5, 0x14, 0x7b, 0x8d, 0xbd, 0x46, 0x84, 0x33, 0x3f, 0x88, 0x5f, 0xc4, 0x1f, 0xe1, 0xc2, 0xec,
	0xae, 0xbd, 0x71, 0x44, 0xec, 0x80, 0xc4, 0x25, 0x79, 0x33, 0xde, 0x79, 0x99, 0xf7, 0x9e, 0xb3,
	0xf0, 0x24, 0x49, 0xb9, 0xe0, 0xe3, 0x88, 0x65, 0xd9, 0x22, 0x60, 0xae, 0xaa, 0xc8, 0xc5, 0x8a,
	0x47, 0xae, 0x60, 0xbe, 0xbf, 0x75, 0xb3, 0xf4, 0x8b, 0x1b, 0x73, 0x11, 0xae, 0xb7, 0xce, 0x4d,
	0x10, 0x8a, 0x87, 0x7c, 0xe9, 0xe2, 0xc3, 0x71, 0xc0, 0x37, 0x8b, 0x38, 0x18, 0xab, 0xe3, 0xcb,
	0x7c, 0x3d, 0x4e, 0xc4, 0x36, 0x61, 0xd9, 0x98, 0x45, 0x08, 0xf4, 0xa7, 0xa6, 0x72, 0x5e, 0x1f,
	0x1f, 0x12, 0x21, 0xfe, 0xba, 0x58, 0x44, 0xc9, 0x0e, 0xe9, 0x61, 0xfa, 0xcb, 0x82, 0xc1, 0x34,
	0xbe, 0xe5, 0x5f, 0xa7, 0x82, 0x45, 0xe4, 0x11, 0x9c, 0x86, 0xbe, 0x6d, 0x8d, 0xac, 0x17, 0x03,
	0x0f, 0x11, 0xb9, 0x80, 0x8e, 0xe0, 0x49, 0xb8, 0xb2, 0x4f, 0x55, 0x4b, 0x17, 0xc4, 0x86, 0xde,
	0x8a, 0xc7, 0x82, 0xc5, 0xc2, 0x6e, 0xa9, 0x7e, 0x59, 0x12, 0x02, 0xed, 0x75, 0xca, 0x23, 0xbb,
	0xad, 0xda, 0x0a, 0xcb, 0xde, 0x1c, 0x97, 0xb0, 0x3b, 0xd8, 0x3b, 0xf7, 0x14, 0x26, 0x97, 0xd0,
	0xcd, 0xe3, 0x94, 0x2d, 0x7c, 0xbb, 0x8b, 0xdd, 0xbe, 0x57, 0x54, 0xe4, 0x25, 0xf4, 0x33, 0x16,
	0xfb, 0x73, 0x5c, 0xd2, 0xee, 0xe1, 0x93, 0xe1, 0xb5, 0xe3, 0x06, 0x9c, 0x07, 0x9b, 0xc2, 0x36,
	0x94, 0xe4, 0xce, 0x4b, 0x05, 0x9e, 0x39, 0x2b, 0xe7, 0x3c, 0x9c, 0x57, 0x73, 0xfd, 0xe3, 0x73,
	0xe5, 0x59, 0xfa, 0x0a, 0xe0, 0x5e, 0x39, 0xaf, 0xd4, 0x1b, 0xb5, 0x56, 0x55, 0x2d, 0xee, 0xea,
	0x33, 0xb1, 0x08, 0x37, 0x85, 0x09, 0x45, 0x45, 0xbf, 0x5b, 0x70, 0x36, 0xc3, 0x05, 0x26, 0x11,
	0x56, 0x1e, 0xfb, 0x2c, 0xc7, 0x99, 0xc4, 0xe5, 0xb8, 0x2a, 0x6a, 0x2c, 0x44, 0xd2, 0x15, 0xaf,
	0x38, 0x58, 0x54, 0xe4, 0x0a, 0x3a, 0x79, 0x2c, 0x90, 0xa3, 0x7d, 0x54, 0x85, 0x3e, 0x48, 0x7f,
	0x14, 0x6b, 0xa8, 0x10, 0xe5, 0x1a, 0x8f, 0xa1, 0x95, 0x9b, 0x10, 0x25, 0xfc, 0x5f, 0x29, 0x8a,
	0x4a, 0x8a, 0x12, 0xef, 0xa5, 0xd5, 0xfd, 0xfb, 0xb4, 0xe8, 0x7b, 0x38, 0x97, 0x1b, 0x6b, 0xe7,
	0xff, 0x65, 0xe5, 0x5d, 0x14, 0xad, 0xbd, 0x28, 0xde, 0x02, 0x48, 0xc2, 0xd9, 0xdd, 0x4c, 0xb2,
	0x8d, 0x60, 0x98, 0x3c, 0xf0, 0x98, 0xdd, 0xe7, 0xd1, 0x92, 0xa5, 0x05, 0x6b, 0xb5, 0x55, 0x95,
	0x7e, 0xba, 0x27, 0x9d, 0x7e, 0x82, 0xe1, 0x1b, 0x26, 0x8c, 0x97, 0xa8, 0x3a, 0xc1, 0xff, 0xac,
	0xe2, 0x40, 0xd5, 0x12, 0xcb, 0x5e, 0x16, 0x7e, 0x63, 0x6a, 0x12, 0x7b, 0x12, 0x1b, 0x77, 0x5a,
	0x15, 0x77, 0x0a, 0x51, 0x6d, 0x23, 0x8a, 0x8e, 0xe0, 0x0c, 0xc9, 0x1b, 0x64, 0x5f, 0xff, 0x6c,
	0x41, 0xef, 0x4e, 0xdf, 0x13, 0x64, 0x0a, 0x03, 0xf3, 0x7a, 0x11, 0xea, 0x1e, 0xba, 0x2f, 0xdc,
	0xea, 0xfb, 0xe7, 0x5c, 0xfe, 0x61, 0xfe, 0x44, 0xde, 0x12, 0xf4, 0xa4, 0xa4, 0x52, 0xb2, 0x9a,
	0xa8, 0x4a, 0xdd, 0x0d, 0x54, 0xef, 0xb4, 0xd5, 0x5a, 0x04, 0x79, 0x5e, 0xcf, 0x65, 0x64, 0x36,
	0x90, 0x4d, 0xa0, 0x57, 0xe4, 0x46, 0x46, 0xf5, 0x4c, 0x3a, 0xd6, 0x06, 0x1a, 0x0f, 0xfa, 0x65,
	0x68, 0xe4, 0xd9, 0x61, 0x9e, 0x4a, 0xa8, 0xce, 0xd3, 0xc3, 0x47, 0xcc, 0x2d, 0x48, 0x4f, 0xae,
	0x2c, 0xf2, 0x01, 0x06, 0x26, 0xab, 0x3a, 0xcb, 0xaa, 0x61, 0x3a, 0x35, 0x02, 0x76, 0xd7, 0x8b,
	0xa4, 0xbd, 0xed, 0x7d, 0xec, 0xe8, 0xf5, 0xbb, 0xea, 0xeb, 0xe6, 0x77, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x51, 0xe9, 0xc9, 0x32, 0x1d, 0x06, 0x00, 0x00,
}
